/*
Navicat MySQL Data Transfer

Source Server         : SIGAF
Source Server Version : 50617
Source Host           : localhost:3306
Source Database       : sigaf

Target Server Type    : MYSQL
Target Server Version : 50617
File Encoding         : 65001

Date: 2014-07-08 22:06:09
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for bitacora
-- ----------------------------
DROP TABLE IF EXISTS `bitacora`;
CREATE TABLE `bitacora` (
  `BI_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Consecutivo',
  `BI_tabla` varchar(25) NOT NULL COMMENT 'Tabla',
  `BI_usuario` varchar(20) NOT NULL COMMENT 'Usuario',
  `BI_operacion` char(3) NOT NULL COMMENT 'Operacion realizada',
  `BI_fecha` datetime NOT NULL COMMENT 'Fecha realizacion cambio',
  `BI_registro` varchar(200) DEFAULT NULL COMMENT 'Registro Insertado/Borrado',
  PRIMARY KEY (`BI_id`),
  UNIQUE KEY `BI_id_UNIQUE` (`BI_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of bitacora
-- ----------------------------

-- ----------------------------
-- Table structure for campus
-- ----------------------------
DROP TABLE IF EXISTS `campus`;
CREATE TABLE `campus` (
  `campus` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Codigo campus',
  `descripcion` varchar(20) NOT NULL COMMENT 'Descripcion CAMPUS.',
  `direccion` varchar(60) DEFAULT NULL COMMENT 'Direccion CAMPUS',
  `ciudad` int(11) NOT NULL COMMENT 'Codigo ciudad',
  PRIMARY KEY (`campus`),
  UNIQUE KEY `CM_codigo_UNIQUE` (`campus`),
  KEY `fk_campus_ciudad1` (`ciudad`),
  CONSTRAINT `fk_campus_ciudad1` FOREIGN KEY (`ciudad`) REFERENCES `ciudad` (`ciudad`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1 COMMENT='<double-click to overwrite multiple objects>';

-- ----------------------------
-- Records of campus
-- ----------------------------
INSERT INTO `campus` VALUES ('1', 'TIJUANA UNIDAD OTAY', 'CALZADA UNIVERSIDAD 14418 PARQUE INDUSTRIAL INTERNACIONAL TI', '16');
INSERT INTO `campus` VALUES ('2', 'TIJUANA UNIDAD TECAT', 'CALZADA UNIVERSIDAD NO.1 FRACC. SAN FERNANDO. C.P. 21460', '16');
INSERT INTO `campus` VALUES ('3', 'TIJUANA UNIDAD ROSAR', 'BLVD. MARIANO VERDUGO NORTE ENTRE CALLE ISLA LOBO VERACRUZ Y', '16');
INSERT INTO `campus` VALUES ('4', 'TIJUANA UNIDAD VALLE', 'BLVD. UNIVERSITARIO #1000', '16');

-- ----------------------------
-- Table structure for caracter
-- ----------------------------
DROP TABLE IF EXISTS `caracter`;
CREATE TABLE `caracter` (
  `caracter` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Caracter de materia uaprendizaje (1,2)',
  `descripcion` varchar(15) NOT NULL COMMENT '1=Obligatoria/2=Optativa',
  PRIMARY KEY (`caracter`),
  UNIQUE KEY `CAR_codigo_UNIQUE` (`caracter`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1 COMMENT='<double-click to overwrite multiple objects>';

-- ----------------------------
-- Records of caracter
-- ----------------------------
INSERT INTO `caracter` VALUES ('1', 'OBLIGATORIA');
INSERT INTO `caracter` VALUES ('2', 'OPTATIVA');

-- ----------------------------
-- Table structure for ciudad
-- ----------------------------
DROP TABLE IF EXISTS `ciudad`;
CREATE TABLE `ciudad` (
  `ciudad` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Codigo Ciudad',
  `descripcion` varchar(60) NOT NULL COMMENT 'Descripcion Ciudad',
  `estado` int(11) NOT NULL COMMENT 'Codigo estado',
  PRIMARY KEY (`ciudad`),
  UNIQUE KEY `CD_codigo_UNIQUE` (`ciudad`),
  KEY `fk_ciudad_estado1` (`estado`),
  CONSTRAINT `fk_ciudad_estado1` FOREIGN KEY (`estado`) REFERENCES `estado` (`estado`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=651 DEFAULT CHARSET=latin1 COMMENT='<double-click to overwrite multiple objects>';

-- ----------------------------
-- Records of ciudad
-- ----------------------------
INSERT INTO `ciudad` VALUES ('1', 'AGUASCALIENTES', '1');
INSERT INTO `ciudad` VALUES ('2', 'ASIENTOS', '1');
INSERT INTO `ciudad` VALUES ('3', 'CALVILLO', '1');
INSERT INTO `ciudad` VALUES ('4', 'COSÃO', '1');
INSERT INTO `ciudad` VALUES ('5', 'JESÃšS MARÃA', '1');
INSERT INTO `ciudad` VALUES ('6', 'PABELLÃ“N DE ARTEAGA', '1');
INSERT INTO `ciudad` VALUES ('7', 'RINCÃ“N DE ROMOS', '1');
INSERT INTO `ciudad` VALUES ('8', 'SAN FRANCISCO DE LOS ROMO', '1');
INSERT INTO `ciudad` VALUES ('9', 'TEPEZALÃ', '1');
INSERT INTO `ciudad` VALUES ('10', 'ENSENADA', '2');
INSERT INTO `ciudad` VALUES ('11', 'MEXICALI', '2');
INSERT INTO `ciudad` VALUES ('12', 'PLAYAS DE ROSARITO', '2');
INSERT INTO `ciudad` VALUES ('13', 'RODOLFO SÃNCHEZ T. (MANEADERO)', '2');
INSERT INTO `ciudad` VALUES ('14', 'SAN FELIPE', '2');
INSERT INTO `ciudad` VALUES ('15', 'TECATE', '2');
INSERT INTO `ciudad` VALUES ('16', 'TIJUANA', '2');
INSERT INTO `ciudad` VALUES ('17', 'CABO SAN LUCAS', '3');
INSERT INTO `ciudad` VALUES ('18', 'CIUDAD CONSTITUCIÃ“N', '3');
INSERT INTO `ciudad` VALUES ('19', 'GUERRERO NEGRO', '3');
INSERT INTO `ciudad` VALUES ('20', 'HEROICA MULEGÃ‰', '3');
INSERT INTO `ciudad` VALUES ('21', 'LA PAZ', '3');
INSERT INTO `ciudad` VALUES ('22', 'LORETO', '3');
INSERT INTO `ciudad` VALUES ('23', 'PUERTO ADOLFO LÃ“PEZ MATEOS', '3');
INSERT INTO `ciudad` VALUES ('24', 'SAN IGNACIO', '3');
INSERT INTO `ciudad` VALUES ('25', 'SAN JOSÃ‰ DEL CABO', '3');
INSERT INTO `ciudad` VALUES ('26', 'TODOS SANTOS', '3');
INSERT INTO `ciudad` VALUES ('27', 'VILLA ALBERTO ANDRÃ‰S ALVARADO ARÃMBURO', '3');
INSERT INTO `ciudad` VALUES ('28', 'CALKINI', '4');
INSERT INTO `ciudad` VALUES ('29', 'CANDELARIA', '4');
INSERT INTO `ciudad` VALUES ('30', 'CHAMPOTÃ“N', '4');
INSERT INTO `ciudad` VALUES ('31', 'CIUDAD DEL CARMEN', '4');
INSERT INTO `ciudad` VALUES ('32', 'ESCÃRCEGA', '4');
INSERT INTO `ciudad` VALUES ('33', 'HECELCHAKÃN', '4');
INSERT INTO `ciudad` VALUES ('34', 'HOPELCHÃ‰N', '4');
INSERT INTO `ciudad` VALUES ('35', 'POMUCH', '4');
INSERT INTO `ciudad` VALUES ('36', 'SABANCUY', '4');
INSERT INTO `ciudad` VALUES ('37', 'SAN FRANCISCO DE CAMPECHE', '4');
INSERT INTO `ciudad` VALUES ('38', 'ALLENDE', '5');
INSERT INTO `ciudad` VALUES ('39', 'ARTEAGA', '5');
INSERT INTO `ciudad` VALUES ('40', 'CASTAÃ‘OS', '5');
INSERT INTO `ciudad` VALUES ('41', 'CIUDAD ACUÃ‘A', '5');
INSERT INTO `ciudad` VALUES ('42', 'CIUDAD MELCHOR MÃšZQUIZ', '5');
INSERT INTO `ciudad` VALUES ('43', 'CUATRO CIÃ‰NEGAS DE CARRANZA', '5');
INSERT INTO `ciudad` VALUES ('44', 'FRANCISCO I. MADERO (CHÃVEZ)', '5');
INSERT INTO `ciudad` VALUES ('45', 'FRONTERA', '5');
INSERT INTO `ciudad` VALUES ('46', 'MATAMOROS', '5');
INSERT INTO `ciudad` VALUES ('47', 'MONCLOVA', '5');
INSERT INTO `ciudad` VALUES ('48', 'MORELOS', '5');
INSERT INTO `ciudad` VALUES ('49', 'NADADORES', '5');
INSERT INTO `ciudad` VALUES ('50', 'NAVA', '5');
INSERT INTO `ciudad` VALUES ('51', 'NUEVA ROSITA', '5');
INSERT INTO `ciudad` VALUES ('52', 'PARRAS DE LA FUENTE', '5');
INSERT INTO `ciudad` VALUES ('53', 'PIEDRAS NEGRAS', '5');
INSERT INTO `ciudad` VALUES ('54', 'RAMOS ARIZPE', '5');
INSERT INTO `ciudad` VALUES ('55', 'SABINAS', '5');
INSERT INTO `ciudad` VALUES ('56', 'SALTILLO', '5');
INSERT INTO `ciudad` VALUES ('57', 'SAN BUENAVENTURA', '5');
INSERT INTO `ciudad` VALUES ('58', 'SAN PEDRO', '5');
INSERT INTO `ciudad` VALUES ('59', 'TORREÃ“N', '5');
INSERT INTO `ciudad` VALUES ('60', 'VIESCA', '5');
INSERT INTO `ciudad` VALUES ('61', 'ZARAGOZA', '5');
INSERT INTO `ciudad` VALUES ('62', 'CIUDAD DE ARMERÃA', '6');
INSERT INTO `ciudad` VALUES ('63', 'CIUDAD DE VILLA DE ÃLVAREZ', '6');
INSERT INTO `ciudad` VALUES ('64', 'CIUDAD DE VILLA DE ÃLVAREZ', '6');
INSERT INTO `ciudad` VALUES ('65', 'COLIMA', '6');
INSERT INTO `ciudad` VALUES ('66', 'MANZANILLO', '6');
INSERT INTO `ciudad` VALUES ('67', 'TECOMAN', '6');
INSERT INTO `ciudad` VALUES ('68', 'ACALA', '7');
INSERT INTO `ciudad` VALUES ('69', 'ARRIAGA', '7');
INSERT INTO `ciudad` VALUES ('70', 'CACAHOATÃN', '7');
INSERT INTO `ciudad` VALUES ('71', 'CHIAPA DE CORZO', '7');
INSERT INTO `ciudad` VALUES ('72', 'CINTALAPA DE FIGUEROA', '7');
INSERT INTO `ciudad` VALUES ('73', 'COMITÃN DE DOMÃNGUEZ', '7');
INSERT INTO `ciudad` VALUES ('74', 'HUIXTLA', '7');
INSERT INTO `ciudad` VALUES ('75', 'JIQUIPILAS', '7');
INSERT INTO `ciudad` VALUES ('76', 'LAS MARGARITAS', '7');
INSERT INTO `ciudad` VALUES ('77', 'LAS ROSAS', '7');
INSERT INTO `ciudad` VALUES ('78', 'MAPASTEPEC', '7');
INSERT INTO `ciudad` VALUES ('79', 'MOTOZINTLA DE MENDOZA', '7');
INSERT INTO `ciudad` VALUES ('80', 'OCOSINGO', '7');
INSERT INTO `ciudad` VALUES ('81', 'OCOZOCOAUTLA DE ESPINOSA', '7');
INSERT INTO `ciudad` VALUES ('82', 'PALENQUE', '7');
INSERT INTO `ciudad` VALUES ('83', 'PICHUCALCO', '7');
INSERT INTO `ciudad` VALUES ('84', 'PIJIJIAPAN', '7');
INSERT INTO `ciudad` VALUES ('85', 'PUERTO MADERO (SAN BENITO)', '7');
INSERT INTO `ciudad` VALUES ('86', 'REFORMA', '7');
INSERT INTO `ciudad` VALUES ('87', 'SAN CRISTÃ“BAL DE LAS CASAS', '7');
INSERT INTO `ciudad` VALUES ('88', 'TAPACHULA DE CÃ“RDOVA Y ORDÃ“Ã‘EZ', '7');
INSERT INTO `ciudad` VALUES ('89', 'TONALÃ', '7');
INSERT INTO `ciudad` VALUES ('90', 'TUXTLA GUTIÃ‰RREZ', '7');
INSERT INTO `ciudad` VALUES ('91', 'VENUSTIANO CARRANZA', '7');
INSERT INTO `ciudad` VALUES ('92', 'VILLAFLORES', '7');
INSERT INTO `ciudad` VALUES ('93', 'BACHÃNIVA', '8');
INSERT INTO `ciudad` VALUES ('94', 'CHIHUAHUA', '8');
INSERT INTO `ciudad` VALUES ('95', 'COLONIA ANÃHUAC', '8');
INSERT INTO `ciudad` VALUES ('96', 'CUAUHTÃ‰MOC', '8');
INSERT INTO `ciudad` VALUES ('97', 'DELICIAS', '8');
INSERT INTO `ciudad` VALUES ('98', 'HIDALGO DEL PARRAL', '8');
INSERT INTO `ciudad` VALUES ('99', 'JOSÃ‰ MARIANO JIMÃ‰NEZ', '8');
INSERT INTO `ciudad` VALUES ('100', 'JUAN ALDAMA', '8');
INSERT INTO `ciudad` VALUES ('101', 'JUÃREZ', '8');
INSERT INTO `ciudad` VALUES ('102', 'MADERA', '8');
INSERT INTO `ciudad` VALUES ('103', 'MANUEL OJINAGA', '8');
INSERT INTO `ciudad` VALUES ('104', 'NUEVO CASAS GRANDES', '8');
INSERT INTO `ciudad` VALUES ('105', 'SANTA ROSALÃA DE CAMARGO', '8');
INSERT INTO `ciudad` VALUES ('106', 'SAUCILLO', '8');
INSERT INTO `ciudad` VALUES ('107', 'CIUDAD DE MÃ‰XICO', '9');
INSERT INTO `ciudad` VALUES ('108', 'CANATLÃN', '10');
INSERT INTO `ciudad` VALUES ('109', 'CIUDAD LERDO', '10');
INSERT INTO `ciudad` VALUES ('110', 'EL SALTO', '10');
INSERT INTO `ciudad` VALUES ('111', 'FRANCISCO I. MADERO', '10');
INSERT INTO `ciudad` VALUES ('112', 'GÃ“MEZ PALACIO', '10');
INSERT INTO `ciudad` VALUES ('113', 'NOMBRE DE DIOS', '10');
INSERT INTO `ciudad` VALUES ('114', 'PEÃ‘Ã“N BLANCO', '10');
INSERT INTO `ciudad` VALUES ('115', 'SAN JUAN DEL RÃO DEL CENTAURO DEL NORTE', '10');
INSERT INTO `ciudad` VALUES ('116', 'SANTA MARÃA DEL ORO', '10');
INSERT INTO `ciudad` VALUES ('117', 'SANTIAGO PAPASQUIARO', '10');
INSERT INTO `ciudad` VALUES ('118', 'VICENTE GUERRERO', '10');
INSERT INTO `ciudad` VALUES ('119', 'VICTORIA DE DURANGO', '10');
INSERT INTO `ciudad` VALUES ('120', 'ABASOLO', '11');
INSERT INTO `ciudad` VALUES ('121', 'ACÃMBARO', '11');
INSERT INTO `ciudad` VALUES ('122', 'APASEO EL ALTO', '11');
INSERT INTO `ciudad` VALUES ('123', 'APASEO EL GRANDE', '11');
INSERT INTO `ciudad` VALUES ('124', 'CELAYA', '11');
INSERT INTO `ciudad` VALUES ('125', 'CIUDAD MANUEL DOBLADO', '11');
INSERT INTO `ciudad` VALUES ('126', 'COMONFORT', '11');
INSERT INTO `ciudad` VALUES ('127', 'CORTAZAR', '11');
INSERT INTO `ciudad` VALUES ('128', 'CUERÃMARO', '11');
INSERT INTO `ciudad` VALUES ('129', 'DOCTOR MORA', '11');
INSERT INTO `ciudad` VALUES ('130', 'DOLORES HIDALGO CUNA DE LA INDEPENDENCIA NACIONAL', '11');
INSERT INTO `ciudad` VALUES ('131', 'EMPALME ESCOBEDO (ESCOBEDO)', '11');
INSERT INTO `ciudad` VALUES ('132', 'GUANAJUATO', '11');
INSERT INTO `ciudad` VALUES ('133', 'HUANÃMARO', '11');
INSERT INTO `ciudad` VALUES ('134', 'IRAPUATO', '11');
INSERT INTO `ciudad` VALUES ('135', 'JARAL DEL PROGRESO', '11');
INSERT INTO `ciudad` VALUES ('136', 'JERÃ‰CUARO', '11');
INSERT INTO `ciudad` VALUES ('137', 'LEÃ“N DE LOS ALDAMA', '11');
INSERT INTO `ciudad` VALUES ('138', 'MARFIL', '11');
INSERT INTO `ciudad` VALUES ('139', 'MOROLEÃ“N', '11');
INSERT INTO `ciudad` VALUES ('140', 'PÃ‰NJAMO', '11');
INSERT INTO `ciudad` VALUES ('141', 'PURÃSIMA DE BUSTOS', '11');
INSERT INTO `ciudad` VALUES ('142', 'RINCÃ“N DE TAMAYO', '11');
INSERT INTO `ciudad` VALUES ('143', 'ROMITA', '11');
INSERT INTO `ciudad` VALUES ('144', 'SALAMANCA', '11');
INSERT INTO `ciudad` VALUES ('145', 'SALVATIERRA', '11');
INSERT INTO `ciudad` VALUES ('146', 'SAN DIEGO DE LA UNIÃ“N', '11');
INSERT INTO `ciudad` VALUES ('147', 'SAN FRANCISCO DEL RINCÃ“N', '11');
INSERT INTO `ciudad` VALUES ('148', 'SAN JOSÃ‰ ITURBIDE', '11');
INSERT INTO `ciudad` VALUES ('149', 'SAN LUIS DE LA PAZ', '11');
INSERT INTO `ciudad` VALUES ('150', 'SAN MIGUEL DE ALLENDE', '11');
INSERT INTO `ciudad` VALUES ('151', 'SANTA CRUZ JUVENTINO ROSAS', '11');
INSERT INTO `ciudad` VALUES ('152', 'SANTIAGO MARAVATÃO', '11');
INSERT INTO `ciudad` VALUES ('153', 'SILAO', '11');
INSERT INTO `ciudad` VALUES ('154', 'TARANDACUAO', '11');
INSERT INTO `ciudad` VALUES ('155', 'URIANGATO', '11');
INSERT INTO `ciudad` VALUES ('156', 'VALLE DE SANTIAGO', '11');
INSERT INTO `ciudad` VALUES ('157', 'VILLAGRÃN', '11');
INSERT INTO `ciudad` VALUES ('158', 'YURIRIA', '11');
INSERT INTO `ciudad` VALUES ('159', 'ACAPULCO DE JUÃREZ', '12');
INSERT INTO `ciudad` VALUES ('160', 'ARCELIA', '12');
INSERT INTO `ciudad` VALUES ('161', 'ATOYAC DE ÃLVAREZ', '12');
INSERT INTO `ciudad` VALUES ('162', 'AYUTLA DE LOS LIBRES', '12');
INSERT INTO `ciudad` VALUES ('163', 'AZOYÃš', '12');
INSERT INTO `ciudad` VALUES ('164', 'BUENAVISTA DE CUELLAR', '12');
INSERT INTO `ciudad` VALUES ('165', 'CHILAPA DE ÃLVAREZ', '12');
INSERT INTO `ciudad` VALUES ('166', 'CHILPANCINGO DE LOS BRAVO', '12');
INSERT INTO `ciudad` VALUES ('167', 'CIUDAD ALTAMIRANO', '12');
INSERT INTO `ciudad` VALUES ('168', 'CIUDAD APAXTLA DE CASTREJÃ“N', '12');
INSERT INTO `ciudad` VALUES ('169', 'COPALA', '12');
INSERT INTO `ciudad` VALUES ('170', 'COYUCA DE BENÃTEZ', '12');
INSERT INTO `ciudad` VALUES ('171', 'COYUCA DE CATALÃN', '12');
INSERT INTO `ciudad` VALUES ('172', 'CRUZ GRANDE', '12');
INSERT INTO `ciudad` VALUES ('173', 'CUAJINICUILAPA', '12');
INSERT INTO `ciudad` VALUES ('174', 'CUTZAMALA DE PINZÃ“N', '12');
INSERT INTO `ciudad` VALUES ('175', 'HUAMUXTITLAN', '12');
INSERT INTO `ciudad` VALUES ('176', 'HUITZUCO', '12');
INSERT INTO `ciudad` VALUES ('177', 'IGUALA DE LA INDEPENDENCIA', '12');
INSERT INTO `ciudad` VALUES ('178', 'LA UNIÃ“N', '12');
INSERT INTO `ciudad` VALUES ('179', 'MARQUELIA', '12');
INSERT INTO `ciudad` VALUES ('180', 'OCOTITO', '12');
INSERT INTO `ciudad` VALUES ('181', 'OLINALÃ', '12');
INSERT INTO `ciudad` VALUES ('182', 'PETATLÃN', '12');
INSERT INTO `ciudad` VALUES ('183', 'SAN JERÃ“NIMO DE JUÃREZ', '12');
INSERT INTO `ciudad` VALUES ('184', 'SAN LUIS ACATLÃN', '12');
INSERT INTO `ciudad` VALUES ('185', 'SAN LUIS DE LA LOMA', '12');
INSERT INTO `ciudad` VALUES ('186', 'SAN LUIS SAN PEDRO', '12');
INSERT INTO `ciudad` VALUES ('187', 'SAN MARCOS', '12');
INSERT INTO `ciudad` VALUES ('188', 'TAXCO DE ALARCÃ“N', '12');
INSERT INTO `ciudad` VALUES ('189', 'TÃ‰CPAN DE GALEANA', '12');
INSERT INTO `ciudad` VALUES ('190', 'TELOLOAPAN', '12');
INSERT INTO `ciudad` VALUES ('191', 'TEPECOACUILCO DE TRUJANO', '12');
INSERT INTO `ciudad` VALUES ('192', 'TIERRA COLORADA', '12');
INSERT INTO `ciudad` VALUES ('193', 'TIXTLA DE GUERRERO', '12');
INSERT INTO `ciudad` VALUES ('194', 'TLALIXTAQUILLA', '12');
INSERT INTO `ciudad` VALUES ('195', 'TLAPA DE COMONFORT', '12');
INSERT INTO `ciudad` VALUES ('196', 'TLAPEHUALA', '12');
INSERT INTO `ciudad` VALUES ('197', 'ZIHUATANEJO', '12');
INSERT INTO `ciudad` VALUES ('198', 'ZUMPANGO DEL RÃO', '12');
INSERT INTO `ciudad` VALUES ('199', 'ACTOPAN', '13');
INSERT INTO `ciudad` VALUES ('200', 'APAN', '13');
INSERT INTO `ciudad` VALUES ('201', 'CIUDAD DE FRAY BERNARDINO DE SAHAGÃšN', '13');
INSERT INTO `ciudad` VALUES ('202', 'CRUZ AZUL', '13');
INSERT INTO `ciudad` VALUES ('203', 'HUEJUTLA DE REYES', '13');
INSERT INTO `ciudad` VALUES ('204', 'IXMIQUILPAN', '13');
INSERT INTO `ciudad` VALUES ('205', 'PACHUCA DE SOTO', '13');
INSERT INTO `ciudad` VALUES ('206', 'SANTIAGO TULANTEPEC', '13');
INSERT INTO `ciudad` VALUES ('207', 'TEPEAPULCO', '13');
INSERT INTO `ciudad` VALUES ('208', 'TEPEJI DEL RIO', '13');
INSERT INTO `ciudad` VALUES ('209', 'TIZAYUCA', '13');
INSERT INTO `ciudad` VALUES ('210', 'TLAXCOAPAN', '13');
INSERT INTO `ciudad` VALUES ('211', 'TULA DE ALLENDE', '13');
INSERT INTO `ciudad` VALUES ('212', 'TULANCINGO', '13');
INSERT INTO `ciudad` VALUES ('213', 'ZIMAPAN', '13');
INSERT INTO `ciudad` VALUES ('214', 'ACATLÃN DE JUÃREZ', '14');
INSERT INTO `ciudad` VALUES ('215', 'AHUALULCO DE MERCADO', '14');
INSERT INTO `ciudad` VALUES ('216', 'AJIJIC', '14');
INSERT INTO `ciudad` VALUES ('217', 'AMECA', '14');
INSERT INTO `ciudad` VALUES ('218', 'ARANDAS', '14');
INSERT INTO `ciudad` VALUES ('219', 'ATOTONILCO EL ALTO', '14');
INSERT INTO `ciudad` VALUES ('220', 'AUTLÃN DE NAVARRO', '14');
INSERT INTO `ciudad` VALUES ('221', 'CHAPALA', '14');
INSERT INTO `ciudad` VALUES ('222', 'CIHUATLÃN', '14');
INSERT INTO `ciudad` VALUES ('223', 'CIUDAD GUZMÃN', '14');
INSERT INTO `ciudad` VALUES ('224', 'COCULA', '14');
INSERT INTO `ciudad` VALUES ('225', 'COLOTLÃN', '14');
INSERT INTO `ciudad` VALUES ('226', 'EL GRULLO', '14');
INSERT INTO `ciudad` VALUES ('227', 'EL QUINCE (SAN JOSÃ‰ EL QUINCE)', '14');
INSERT INTO `ciudad` VALUES ('228', 'ETZATLÃN', '14');
INSERT INTO `ciudad` VALUES ('229', 'GUADALAJARA', '14');
INSERT INTO `ciudad` VALUES ('230', 'HUEJUQUILLA EL ALTO', '14');
INSERT INTO `ciudad` VALUES ('231', 'JALOSTOTITLÃN', '14');
INSERT INTO `ciudad` VALUES ('232', 'JAMAY', '14');
INSERT INTO `ciudad` VALUES ('233', 'JOCOTEPEC', '14');
INSERT INTO `ciudad` VALUES ('234', 'LA BARCA', '14');
INSERT INTO `ciudad` VALUES ('235', 'LA RESOLANA', '14');
INSERT INTO `ciudad` VALUES ('236', 'LAGOS DE MORENO', '14');
INSERT INTO `ciudad` VALUES ('237', 'LAS PINTITAS', '14');
INSERT INTO `ciudad` VALUES ('238', 'MAGDALENA', '14');
INSERT INTO `ciudad` VALUES ('239', 'OCOTLÃN', '14');
INSERT INTO `ciudad` VALUES ('240', 'PONCITLÃN', '14');
INSERT INTO `ciudad` VALUES ('241', 'PUERTO VALLARTA', '14');
INSERT INTO `ciudad` VALUES ('242', 'SAN DIEGO DE ALEJANDRÃA', '14');
INSERT INTO `ciudad` VALUES ('243', 'SAN IGNACIO CERRO GORDO', '14');
INSERT INTO `ciudad` VALUES ('244', 'SAN JOSÃ‰ EL VERDE (EL VERDE)', '14');
INSERT INTO `ciudad` VALUES ('245', 'SAN JUAN DE LOS LAGOS', '14');
INSERT INTO `ciudad` VALUES ('246', 'SAN JULIÃN', '14');
INSERT INTO `ciudad` VALUES ('247', 'SAN MIGUEL EL ALTO', '14');
INSERT INTO `ciudad` VALUES ('248', 'SAYULA', '14');
INSERT INTO `ciudad` VALUES ('249', 'TALA', '14');
INSERT INTO `ciudad` VALUES ('250', 'TALPA DE ALLENDE', '14');
INSERT INTO `ciudad` VALUES ('251', 'TAMAZULA DE GORDIANO', '14');
INSERT INTO `ciudad` VALUES ('252', 'TECALITLÃN', '14');
INSERT INTO `ciudad` VALUES ('253', 'TEOCALTICHE', '14');
INSERT INTO `ciudad` VALUES ('254', 'TEPATITLÃN DE MORELOS', '14');
INSERT INTO `ciudad` VALUES ('255', 'TEQUILA', '14');
INSERT INTO `ciudad` VALUES ('256', 'TLAJOMULCO DE ZÃšÃ‘IGA', '14');
INSERT INTO `ciudad` VALUES ('257', 'TLAQUEPAQUE', '14');
INSERT INTO `ciudad` VALUES ('258', 'TONALÃ', '14');
INSERT INTO `ciudad` VALUES ('259', 'TOTOTLÃN', '14');
INSERT INTO `ciudad` VALUES ('260', 'TUXPAN', '14');
INSERT INTO `ciudad` VALUES ('261', 'UNIÃ“N DE SAN ANTONIO', '14');
INSERT INTO `ciudad` VALUES ('262', 'VALLE DE GUADALUPE', '14');
INSERT INTO `ciudad` VALUES ('263', 'VILLA CORONA', '14');
INSERT INTO `ciudad` VALUES ('264', 'VILLA HIDALGO', '14');
INSERT INTO `ciudad` VALUES ('265', 'YAHUALICA DE GONZÃLEZ GALLO', '14');
INSERT INTO `ciudad` VALUES ('266', 'ZACOALCO DE TORRES', '14');
INSERT INTO `ciudad` VALUES ('267', 'ZAPOPAN', '14');
INSERT INTO `ciudad` VALUES ('268', 'ZAPOTILTIC', '14');
INSERT INTO `ciudad` VALUES ('269', 'ALMOLOYA DE JUÃREZ', '15');
INSERT INTO `ciudad` VALUES ('270', 'AMATEPEC', '15');
INSERT INTO `ciudad` VALUES ('271', 'CAPULHUAC', '15');
INSERT INTO `ciudad` VALUES ('272', 'CHALCO DE DÃAZ COVARRUBIAS', '15');
INSERT INTO `ciudad` VALUES ('273', 'CHICONCUAC', '15');
INSERT INTO `ciudad` VALUES ('274', 'CHIMALHUACÃN', '15');
INSERT INTO `ciudad` VALUES ('275', 'CIUDAD ADOLFO LÃ“PEZ MATEOS', '15');
INSERT INTO `ciudad` VALUES ('276', 'CIUDAD NEZAHUALCOYOTL', '15');
INSERT INTO `ciudad` VALUES ('277', 'COACALCO DE BERRIOZABAL', '15');
INSERT INTO `ciudad` VALUES ('278', 'CUAUTITLÃN', '15');
INSERT INTO `ciudad` VALUES ('279', 'CUAUTITLÃN IZCALLI', '15');
INSERT INTO `ciudad` VALUES ('280', 'ECATEPEC DE MORELOS', '15');
INSERT INTO `ciudad` VALUES ('281', 'HUIXQUILUCAN DE DEGOLLADO', '15');
INSERT INTO `ciudad` VALUES ('282', 'IXTAPALUCA', '15');
INSERT INTO `ciudad` VALUES ('283', 'JUCHITEPEC DE MARIANO RIVA PALACIO', '15');
INSERT INTO `ciudad` VALUES ('284', 'LOS REYES ACAQUILPAN (LA PAZ)', '15');
INSERT INTO `ciudad` VALUES ('285', 'MELCHOR OCAMPO', '15');
INSERT INTO `ciudad` VALUES ('286', 'METEPEC', '15');
INSERT INTO `ciudad` VALUES ('287', 'NAUCALPAN DE JUÃREZ', '15');
INSERT INTO `ciudad` VALUES ('288', 'OCOYOACAC', '15');
INSERT INTO `ciudad` VALUES ('289', 'SAN MATEO ATENCO', '15');
INSERT INTO `ciudad` VALUES ('290', 'SAN VICENTE CHICOLOAPAN DE JUÃREZ', '15');
INSERT INTO `ciudad` VALUES ('291', 'SANTA MARIA TULTEPEC', '15');
INSERT INTO `ciudad` VALUES ('292', 'TECAMAC DE FELIPE VILLANUEVA', '15');
INSERT INTO `ciudad` VALUES ('293', 'TEJUPILCO DE HIDALGO', '15');
INSERT INTO `ciudad` VALUES ('294', 'TEPOTZOTLÃN', '15');
INSERT INTO `ciudad` VALUES ('295', 'TEQUIXQUIAC', '15');
INSERT INTO `ciudad` VALUES ('296', 'TEXCOCO DE MORA', '15');
INSERT INTO `ciudad` VALUES ('297', 'TLALNEPANTLA DE BAZ', '15');
INSERT INTO `ciudad` VALUES ('298', 'TOLUCA DE LERDO', '15');
INSERT INTO `ciudad` VALUES ('299', 'TULTITLÃN DE MARIANO ESCOBEDO', '15');
INSERT INTO `ciudad` VALUES ('300', 'VALLE DE CHALCO SOLIDARIDAD', '15');
INSERT INTO `ciudad` VALUES ('301', 'VILLA NICOLÃS ROMERO', '15');
INSERT INTO `ciudad` VALUES ('302', 'XONACATLÃN', '15');
INSERT INTO `ciudad` VALUES ('303', 'ZUMPANGO', '15');
INSERT INTO `ciudad` VALUES ('304', 'APATZINGÃN DE LA CONSTITUCIÃ“N', '16');
INSERT INTO `ciudad` VALUES ('305', 'CIUDAD HIDALGO', '16');
INSERT INTO `ciudad` VALUES ('306', 'CIUDAD LÃZARO CÃRDENAS', '16');
INSERT INTO `ciudad` VALUES ('307', 'COTIJA DE LA PAZ', '16');
INSERT INTO `ciudad` VALUES ('308', 'CUITZEO DEL PORVENIR', '16');
INSERT INTO `ciudad` VALUES ('309', 'HEROICA ZITÃCUARO', '16');
INSERT INTO `ciudad` VALUES ('310', 'HUETAMO DE NÃšÃ‘EZ', '16');
INSERT INTO `ciudad` VALUES ('311', 'JACONA DE PLANCARTE', '16');
INSERT INTO `ciudad` VALUES ('312', 'JIQUILPAN DE JUÃREZ', '16');
INSERT INTO `ciudad` VALUES ('313', 'LA PIEDAD DE CABADAS', '16');
INSERT INTO `ciudad` VALUES ('314', 'LAS GUACAMAYAS', '16');
INSERT INTO `ciudad` VALUES ('315', 'LOS REYES DE SALGADO', '16');
INSERT INTO `ciudad` VALUES ('316', 'MARAVATÃO DE OCAMPO', '16');
INSERT INTO `ciudad` VALUES ('317', 'MORELIA', '16');
INSERT INTO `ciudad` VALUES ('318', 'NUEVA ITALIA DE RUIZ', '16');
INSERT INTO `ciudad` VALUES ('319', 'PARACHO DE VERDUZCO', '16');
INSERT INTO `ciudad` VALUES ('320', 'PÃTZCUARO', '16');
INSERT INTO `ciudad` VALUES ('321', 'PURUÃNDIRO', '16');
INSERT INTO `ciudad` VALUES ('322', 'SAHUAYO DE MORELOS', '16');
INSERT INTO `ciudad` VALUES ('323', 'TACÃMBARO DE CODALLOS', '16');
INSERT INTO `ciudad` VALUES ('324', 'TANGANCÃCUARO DE ARISTA', '16');
INSERT INTO `ciudad` VALUES ('325', 'TUXPAN', '16');
INSERT INTO `ciudad` VALUES ('326', 'URUAPAN', '16');
INSERT INTO `ciudad` VALUES ('327', 'YURÃ‰CUARO', '16');
INSERT INTO `ciudad` VALUES ('328', 'ZACAPU', '16');
INSERT INTO `ciudad` VALUES ('329', 'ZAMORA DE HIDALGO', '16');
INSERT INTO `ciudad` VALUES ('330', 'ZINAPÃ‰CUARO DE FIGUEROA', '16');
INSERT INTO `ciudad` VALUES ('331', 'CUAUTLA (CUAUTLA DE MORELOS)', '17');
INSERT INTO `ciudad` VALUES ('332', 'CUERNAVACA', '17');
INSERT INTO `ciudad` VALUES ('333', 'GALEANA', '17');
INSERT INTO `ciudad` VALUES ('334', 'JOJUTLA', '17');
INSERT INTO `ciudad` VALUES ('335', 'PUENTE DE IXTLA', '17');
INSERT INTO `ciudad` VALUES ('336', 'SANTA ROSA TREINTA', '17');
INSERT INTO `ciudad` VALUES ('337', 'TLAQUILTENANGO', '17');
INSERT INTO `ciudad` VALUES ('338', 'ZACATEPEC DE HIDALGO', '17');
INSERT INTO `ciudad` VALUES ('339', 'ACAPONETA', '18');
INSERT INTO `ciudad` VALUES ('340', 'AHUACATLÃN', '18');
INSERT INTO `ciudad` VALUES ('341', 'BUCERÃAS', '18');
INSERT INTO `ciudad` VALUES ('342', 'COMPOSTELA', '18');
INSERT INTO `ciudad` VALUES ('343', 'FRANCISCO I. MADERO (PUGA)', '18');
INSERT INTO `ciudad` VALUES ('344', 'IXTLÃN DEL RÃO', '18');
INSERT INTO `ciudad` VALUES ('345', 'JALA', '18');
INSERT INTO `ciudad` VALUES ('346', 'LA PEÃ‘ITA DE JALTEMBA', '18');
INSERT INTO `ciudad` VALUES ('347', 'LAS VARAS', '18');
INSERT INTO `ciudad` VALUES ('348', 'RUIZ', '18');
INSERT INTO `ciudad` VALUES ('349', 'SAN BLAS', '18');
INSERT INTO `ciudad` VALUES ('350', 'SAN PEDRO LAGUNILLAS', '18');
INSERT INTO `ciudad` VALUES ('351', 'SANTIAGO IXCUINTLA', '18');
INSERT INTO `ciudad` VALUES ('352', 'TECUALA', '18');
INSERT INTO `ciudad` VALUES ('353', 'TEPIC', '18');
INSERT INTO `ciudad` VALUES ('354', 'TUXPAN', '18');
INSERT INTO `ciudad` VALUES ('355', 'VILLA HIDALGO (EL NUEVO)', '18');
INSERT INTO `ciudad` VALUES ('356', 'XALISCO', '18');
INSERT INTO `ciudad` VALUES ('357', 'ANÃHUAC', '19');
INSERT INTO `ciudad` VALUES ('358', 'CADEREYTA JIMÃ‰NEZ', '19');
INSERT INTO `ciudad` VALUES ('359', 'CIÃ‰NEGA DE FLORES', '19');
INSERT INTO `ciudad` VALUES ('360', 'CIUDAD APODACA', '19');
INSERT INTO `ciudad` VALUES ('361', 'CIUDAD BENITO JUÃREZ', '19');
INSERT INTO `ciudad` VALUES ('362', 'CIUDAD GENERAL ESCOBEDO', '19');
INSERT INTO `ciudad` VALUES ('363', 'CIUDAD SABINAS HIDALGO', '19');
INSERT INTO `ciudad` VALUES ('364', 'CIUDAD SANTA CATARINA', '19');
INSERT INTO `ciudad` VALUES ('365', 'CIUDAD SANTA CATARINA', '19');
INSERT INTO `ciudad` VALUES ('366', 'DOCTOR ARROYO', '19');
INSERT INTO `ciudad` VALUES ('367', 'EL CERCADO', '19');
INSERT INTO `ciudad` VALUES ('368', 'GARCÃA', '19');
INSERT INTO `ciudad` VALUES ('369', 'GUADALUPE', '19');
INSERT INTO `ciudad` VALUES ('370', 'HUALAHUISES', '19');
INSERT INTO `ciudad` VALUES ('371', 'LINARES', '19');
INSERT INTO `ciudad` VALUES ('372', 'MONTEMORELOS', '19');
INSERT INTO `ciudad` VALUES ('373', 'MONTERREY', '19');
INSERT INTO `ciudad` VALUES ('374', 'SAN NICOLÃS DE LOS GARZA', '19');
INSERT INTO `ciudad` VALUES ('375', 'SAN PEDRO GARZA GARCÃA', '19');
INSERT INTO `ciudad` VALUES ('376', 'SANTIAGO', '19');
INSERT INTO `ciudad` VALUES ('377', 'ASUNCIÃ“N NOCHIXTLÃN', '20');
INSERT INTO `ciudad` VALUES ('378', 'BAHIAS DE HUATULCO', '20');
INSERT INTO `ciudad` VALUES ('379', 'CHAHUITES', '20');
INSERT INTO `ciudad` VALUES ('380', 'CIUDAD IXTEPEC', '20');
INSERT INTO `ciudad` VALUES ('381', 'COSOLAPA', '20');
INSERT INTO `ciudad` VALUES ('382', 'CUILÃPAM DE GUERRERO', '20');
INSERT INTO `ciudad` VALUES ('383', 'EL CAMARÃ“N', '20');
INSERT INTO `ciudad` VALUES ('384', 'EL ROSARIO', '20');
INSERT INTO `ciudad` VALUES ('385', 'HEROICA CIUDAD DE EJUTLA DE CRESPO', '20');
INSERT INTO `ciudad` VALUES ('386', 'HEROICA CIUDAD DE HUAJUAPAN DE LEÃ“N', '20');
INSERT INTO `ciudad` VALUES ('387', 'HEROICA CIUDAD DE TLAXIACO', '20');
INSERT INTO `ciudad` VALUES ('388', 'JUCHITÃN (JUCHITÃN DE ZARAGOZA)', '20');
INSERT INTO `ciudad` VALUES ('389', 'LAGUNAS', '20');
INSERT INTO `ciudad` VALUES ('390', 'LOMA BONITA', '20');
INSERT INTO `ciudad` VALUES ('391', 'MARISCALA DE JUÃREZ', '20');
INSERT INTO `ciudad` VALUES ('392', 'MATÃAS ROMERO AVENDAÃ‘O', '20');
INSERT INTO `ciudad` VALUES ('393', 'MIAHUATLÃN DE PORFIRIO DÃAZ', '20');
INSERT INTO `ciudad` VALUES ('394', 'NATIVIDAD', '20');
INSERT INTO `ciudad` VALUES ('395', 'OAXACA DE JUÃREZ', '20');
INSERT INTO `ciudad` VALUES ('396', 'OCOTLÃN DE MORELOS', '20');
INSERT INTO `ciudad` VALUES ('397', 'PUERTO ESCONDIDO', '20');
INSERT INTO `ciudad` VALUES ('398', 'PUTLA VILLA DE GUERRERO', '20');
INSERT INTO `ciudad` VALUES ('399', 'RÃO GRANDE O PIEDRA PARADA', '20');
INSERT INTO `ciudad` VALUES ('400', 'SALINA CRUZ', '20');
INSERT INTO `ciudad` VALUES ('401', 'SAN ANTONIO DE LA CAL', '20');
INSERT INTO `ciudad` VALUES ('402', 'SAN BLAS ATEMPA', '20');
INSERT INTO `ciudad` VALUES ('403', 'SAN FELIPE JALAPA DE DÃAZ', '20');
INSERT INTO `ciudad` VALUES ('404', 'SAN FRANCISCO IXHUATÃN', '20');
INSERT INTO `ciudad` VALUES ('405', 'SAN FRANCISCO TELIXTLAHUACA', '20');
INSERT INTO `ciudad` VALUES ('406', 'SAN JUAN BAUTISTA CUICATLÃN', '20');
INSERT INTO `ciudad` VALUES ('407', 'SAN JUAN BAUTISTA LO DE SOTO', '20');
INSERT INTO `ciudad` VALUES ('408', 'SAN JUAN BAUTISTA TUXTEPEC', '20');
INSERT INTO `ciudad` VALUES ('409', 'SAN JUAN BAUTISTA VALLE NACIONAL', '20');
INSERT INTO `ciudad` VALUES ('410', 'SAN JUAN CACAHUATEPEC', '20');
INSERT INTO `ciudad` VALUES ('411', 'SAN MIGUEL EL GRANDE', '20');
INSERT INTO `ciudad` VALUES ('412', 'SAN PABLO HUITZO', '20');
INSERT INTO `ciudad` VALUES ('413', 'SAN PABLO VILLA DE MITLA', '20');
INSERT INTO `ciudad` VALUES ('414', 'SAN PEDRO MIXTEPEC -DTO. 22-', '20');
INSERT INTO `ciudad` VALUES ('415', 'SAN PEDRO POCHUTLA', '20');
INSERT INTO `ciudad` VALUES ('416', 'SAN PEDRO TAPANATEPEC', '20');
INSERT INTO `ciudad` VALUES ('417', 'SAN PEDRO TOTOLAPA', '20');
INSERT INTO `ciudad` VALUES ('418', 'SAN SEBASTIÃN TECOMAXTLAHUACA', '20');
INSERT INTO `ciudad` VALUES ('419', 'SANTA CRUZ ITUNDUJIA', '20');
INSERT INTO `ciudad` VALUES ('420', 'SANTA LUCIA DEL CAMINO', '20');
INSERT INTO `ciudad` VALUES ('421', 'SANTA MARÃA HUATULCO', '20');
INSERT INTO `ciudad` VALUES ('422', 'SANTIAGO JAMILTEPEC', '20');
INSERT INTO `ciudad` VALUES ('423', 'SANTIAGO JUXTLAHUACA', '20');
INSERT INTO `ciudad` VALUES ('424', 'SANTIAGO PINOTEPA NACIONAL', '20');
INSERT INTO `ciudad` VALUES ('425', 'SANTIAGO SUCHILQUITONGO', '20');
INSERT INTO `ciudad` VALUES ('426', 'SANTO DOMINGO TEHUANTEPEC', '20');
INSERT INTO `ciudad` VALUES ('427', 'TEOTITLÃN DE FLORES MAGÃ“N', '20');
INSERT INTO `ciudad` VALUES ('428', 'TLACOLULA DE MATAMOROS', '20');
INSERT INTO `ciudad` VALUES ('429', 'UNIÃ“N HIDALGO', '20');
INSERT INTO `ciudad` VALUES ('430', 'VICENTE CAMALOTE', '20');
INSERT INTO `ciudad` VALUES ('431', 'VILLA DE TAMAZULÃPAM DEL PROGRESO', '20');
INSERT INTO `ciudad` VALUES ('432', 'VILLA DE ZAACHILA', '20');
INSERT INTO `ciudad` VALUES ('433', 'VILLA SOLA DE VEGA', '20');
INSERT INTO `ciudad` VALUES ('434', 'ZIMATLÃN DE ÃLVAREZ', '20');
INSERT INTO `ciudad` VALUES ('435', 'ACATLÃN DE OSORIO', '21');
INSERT INTO `ciudad` VALUES ('436', 'AMOZOC', '21');
INSERT INTO `ciudad` VALUES ('437', 'ATLIXCO', '21');
INSERT INTO `ciudad` VALUES ('438', 'CIUDAD SERDÃN', '21');
INSERT INTO `ciudad` VALUES ('439', 'CUAUTLANCINGO', '21');
INSERT INTO `ciudad` VALUES ('440', 'HUAUCHINANGO', '21');
INSERT INTO `ciudad` VALUES ('441', 'IZÃšCAR DE MATAMOROS', '21');
INSERT INTO `ciudad` VALUES ('442', 'PUEBLA (HEROICA PUEBLA)', '21');
INSERT INTO `ciudad` VALUES ('443', 'SAN ANDRÃ‰S CHOLULA', '21');
INSERT INTO `ciudad` VALUES ('444', 'SAN MARTÃN TEXMELUCAN DE LABASTIDA', '21');
INSERT INTO `ciudad` VALUES ('445', 'SAN PEDRO CHOLULA', '21');
INSERT INTO `ciudad` VALUES ('446', 'TECAMACHALCO', '21');
INSERT INTO `ciudad` VALUES ('447', 'TEHUACAN', '21');
INSERT INTO `ciudad` VALUES ('448', 'TEPEACA', '21');
INSERT INTO `ciudad` VALUES ('449', 'TEZIUTLAN', '21');
INSERT INTO `ciudad` VALUES ('450', 'XICOTEPEC', '21');
INSERT INTO `ciudad` VALUES ('451', 'ZACATLÃN', '21');
INSERT INTO `ciudad` VALUES ('452', 'EL PUEBLITO', '22');
INSERT INTO `ciudad` VALUES ('453', 'QUERÃ‰TARO', '22');
INSERT INTO `ciudad` VALUES ('454', 'SAN JUAN DEL RIO', '22');
INSERT INTO `ciudad` VALUES ('455', 'BACALAR', '23');
INSERT INTO `ciudad` VALUES ('456', 'CANCÃšN', '23');
INSERT INTO `ciudad` VALUES ('457', 'CHETUMAL', '23');
INSERT INTO `ciudad` VALUES ('458', 'COZUMEL', '23');
INSERT INTO `ciudad` VALUES ('459', 'FELIPE CARRILLO PUERTO', '23');
INSERT INTO `ciudad` VALUES ('460', 'ISLA MUJERES', '23');
INSERT INTO `ciudad` VALUES ('461', 'KANTUNILKÃN', '23');
INSERT INTO `ciudad` VALUES ('462', 'PLAYA DEL CARMEN', '23');
INSERT INTO `ciudad` VALUES ('463', 'CÃRDENAS', '24');
INSERT INTO `ciudad` VALUES ('464', 'CEDRAL', '24');
INSERT INTO `ciudad` VALUES ('465', 'CERRITOS', '24');
INSERT INTO `ciudad` VALUES ('466', 'CHARCAS', '24');
INSERT INTO `ciudad` VALUES ('467', 'CIUDAD DEL MAÃZ', '24');
INSERT INTO `ciudad` VALUES ('468', 'CIUDAD VALLES', '24');
INSERT INTO `ciudad` VALUES ('469', 'Ã‰BANO', '24');
INSERT INTO `ciudad` VALUES ('470', 'EL NARANJO', '24');
INSERT INTO `ciudad` VALUES ('471', 'FRACCIÃ“N EL REFUGIO', '24');
INSERT INTO `ciudad` VALUES ('472', 'MATEHUALA', '24');
INSERT INTO `ciudad` VALUES ('473', 'RIOVERDE', '24');
INSERT INTO `ciudad` VALUES ('474', 'SALINAS DE HIDALGO', '24');
INSERT INTO `ciudad` VALUES ('475', 'SAN LUIS POTOSÃ', '24');
INSERT INTO `ciudad` VALUES ('476', 'SANTA MARÃA DEL RÃO', '24');
INSERT INTO `ciudad` VALUES ('477', 'SOLEDAD DE GRACIANO SÃNCHEZ', '24');
INSERT INTO `ciudad` VALUES ('478', 'TAMASOPO', '24');
INSERT INTO `ciudad` VALUES ('479', 'TAMAZUNCHALE', '24');
INSERT INTO `ciudad` VALUES ('480', 'TAMUIN', '24');
INSERT INTO `ciudad` VALUES ('481', 'TIERRA NUEVA', '24');
INSERT INTO `ciudad` VALUES ('482', 'VILLA DE REYES', '24');
INSERT INTO `ciudad` VALUES ('483', 'AGUARUTO', '25');
INSERT INTO `ciudad` VALUES ('484', 'AHOME', '25');
INSERT INTO `ciudad` VALUES ('485', 'ANGOSTURA', '25');
INSERT INTO `ciudad` VALUES ('486', 'CHOIX', '25');
INSERT INTO `ciudad` VALUES ('487', 'COSALÃ', '25');
INSERT INTO `ciudad` VALUES ('488', 'CULIACÃN ROSALES', '25');
INSERT INTO `ciudad` VALUES ('489', 'EL ROSARIO', '25');
INSERT INTO `ciudad` VALUES ('490', 'ESCUINAPA DE HIDALGO', '25');
INSERT INTO `ciudad` VALUES ('491', 'ESTACIÃ“N NARANJO', '25');
INSERT INTO `ciudad` VALUES ('492', 'GUAMÃšCHIL', '25');
INSERT INTO `ciudad` VALUES ('493', 'GUASAVE', '25');
INSERT INTO `ciudad` VALUES ('494', 'HIGUERA DE ZARAGOZA', '25');
INSERT INTO `ciudad` VALUES ('495', 'LA CRUZ', '25');
INSERT INTO `ciudad` VALUES ('496', 'LIC. BENITO JUÃREZ (CAMPO GOBIERNO)', '25');
INSERT INTO `ciudad` VALUES ('497', 'LOS MOCHIS', '25');
INSERT INTO `ciudad` VALUES ('498', 'MAZATLÃN', '25');
INSERT INTO `ciudad` VALUES ('499', 'MOCORITO', '25');
INSERT INTO `ciudad` VALUES ('500', 'NAVOLATO', '25');
INSERT INTO `ciudad` VALUES ('501', 'QUILA', '25');
INSERT INTO `ciudad` VALUES ('502', 'SAN BLAS', '25');
INSERT INTO `ciudad` VALUES ('503', 'SAN IGNACIO', '25');
INSERT INTO `ciudad` VALUES ('504', 'SINALOA DE LEYVA', '25');
INSERT INTO `ciudad` VALUES ('505', 'TOPOLOBAMPO', '25');
INSERT INTO `ciudad` VALUES ('506', 'VILLA UNIÃ“N', '25');
INSERT INTO `ciudad` VALUES ('507', 'AGUA PRIETA', '26');
INSERT INTO `ciudad` VALUES ('508', 'CIUDAD OBREGÃ“N', '26');
INSERT INTO `ciudad` VALUES ('509', 'EMPALME', '26');
INSERT INTO `ciudad` VALUES ('510', 'HERMOSILLO', '26');
INSERT INTO `ciudad` VALUES ('511', 'HEROICA CABORCA', '26');
INSERT INTO `ciudad` VALUES ('512', 'HEROICA CIUDAD DE CANANEA', '26');
INSERT INTO `ciudad` VALUES ('513', 'HEROICA GUAYMAS', '26');
INSERT INTO `ciudad` VALUES ('514', 'HEROICA NOGALES', '26');
INSERT INTO `ciudad` VALUES ('515', 'HUATABAMPO', '26');
INSERT INTO `ciudad` VALUES ('516', 'MAGDALENA DE KINO', '26');
INSERT INTO `ciudad` VALUES ('517', 'NAVOJOA', '26');
INSERT INTO `ciudad` VALUES ('518', 'PUERTO PEÃ‘ASCO', '26');
INSERT INTO `ciudad` VALUES ('519', 'SAN LUIS RÃO COLORADO', '26');
INSERT INTO `ciudad` VALUES ('520', 'SONOITA', '26');
INSERT INTO `ciudad` VALUES ('521', 'CÃRDENAS', '27');
INSERT INTO `ciudad` VALUES ('522', 'COMALCALCO', '27');
INSERT INTO `ciudad` VALUES ('523', 'CUNDUACÃN', '27');
INSERT INTO `ciudad` VALUES ('524', 'EMILIANO ZAPATA', '27');
INSERT INTO `ciudad` VALUES ('525', 'FRONTERA', '27');
INSERT INTO `ciudad` VALUES ('526', 'HUIMANGUILLO', '27');
INSERT INTO `ciudad` VALUES ('527', 'JALPA DE MÃ‰NDEZ', '27');
INSERT INTO `ciudad` VALUES ('528', 'MACUSPANA', '27');
INSERT INTO `ciudad` VALUES ('529', 'PARAÃSO', '27');
INSERT INTO `ciudad` VALUES ('530', 'TEAPA', '27');
INSERT INTO `ciudad` VALUES ('531', 'TENOSIQUE DE PINO SUÃREZ', '27');
INSERT INTO `ciudad` VALUES ('532', 'VILLAHERMOSA', '27');
INSERT INTO `ciudad` VALUES ('533', 'ALTAMIRA', '28');
INSERT INTO `ciudad` VALUES ('534', 'CIUDAD CAMARGO', '28');
INSERT INTO `ciudad` VALUES ('535', 'CIUDAD GUSTAVO DÃAZ ORDAZ', '28');
INSERT INTO `ciudad` VALUES ('536', 'CIUDAD MADERO', '28');
INSERT INTO `ciudad` VALUES ('537', 'CIUDAD MANTE', '28');
INSERT INTO `ciudad` VALUES ('538', 'CIUDAD MIGUEL ALEMÃN', '28');
INSERT INTO `ciudad` VALUES ('539', 'CIUDAD RÃO BRAVO', '28');
INSERT INTO `ciudad` VALUES ('540', 'CIUDAD TULA', '28');
INSERT INTO `ciudad` VALUES ('541', 'CIUDAD VICTORIA', '28');
INSERT INTO `ciudad` VALUES ('542', 'ESTACIÃ“N MANUEL (ÃšRSULO GALVÃN)', '28');
INSERT INTO `ciudad` VALUES ('543', 'GONZÃLEZ', '28');
INSERT INTO `ciudad` VALUES ('544', 'HEROICA MATAMOROS', '28');
INSERT INTO `ciudad` VALUES ('545', 'JAUMAVE', '28');
INSERT INTO `ciudad` VALUES ('546', 'NUEVA CIUDAD GUERRERO', '28');
INSERT INTO `ciudad` VALUES ('547', 'NUEVO LAREDO', '28');
INSERT INTO `ciudad` VALUES ('548', 'REYNOSA', '28');
INSERT INTO `ciudad` VALUES ('549', 'SAN FERNANDO', '28');
INSERT INTO `ciudad` VALUES ('550', 'SOTO LA MARINA', '28');
INSERT INTO `ciudad` VALUES ('551', 'TAMPICO', '28');
INSERT INTO `ciudad` VALUES ('552', 'VALLE HERMOSO', '28');
INSERT INTO `ciudad` VALUES ('553', 'XICOTÃ‰NCATL', '28');
INSERT INTO `ciudad` VALUES ('554', 'APIZACO', '29');
INSERT INTO `ciudad` VALUES ('555', 'CALPULALPAN', '29');
INSERT INTO `ciudad` VALUES ('556', 'CHIAUTEMPAN', '29');
INSERT INTO `ciudad` VALUES ('557', 'HUAMANTLA', '29');
INSERT INTO `ciudad` VALUES ('558', 'TLAXCALA (TLAXCALA DE XICOTENCATL)', '29');
INSERT INTO `ciudad` VALUES ('559', 'VILLA VICENTE GUERRERO', '29');
INSERT INTO `ciudad` VALUES ('560', 'ACAYUCAN', '30');
INSERT INTO `ciudad` VALUES ('561', 'AGUA DULCE', '30');
INSERT INTO `ciudad` VALUES ('562', 'ALTOTONGA', '30');
INSERT INTO `ciudad` VALUES ('563', 'ALVARADO', '30');
INSERT INTO `ciudad` VALUES ('564', 'ÃNGEL R. CABADA', '30');
INSERT INTO `ciudad` VALUES ('565', 'ATOYAC', '30');
INSERT INTO `ciudad` VALUES ('566', 'BANDERILLA', '30');
INSERT INTO `ciudad` VALUES ('567', 'BOCA DEL RÃO', '30');
INSERT INTO `ciudad` VALUES ('568', 'CARLOS A. CARRILLO', '30');
INSERT INTO `ciudad` VALUES ('569', 'CATEMACO', '30');
INSERT INTO `ciudad` VALUES ('570', 'CAZONES DE HERRERA', '30');
INSERT INTO `ciudad` VALUES ('571', 'CERRO AZUL', '30');
INSERT INTO `ciudad` VALUES ('572', 'COATEPEC', '30');
INSERT INTO `ciudad` VALUES ('573', 'COATZACOALCOS', '30');
INSERT INTO `ciudad` VALUES ('574', 'COATZINTLA', '30');
INSERT INTO `ciudad` VALUES ('575', 'CÃ“RDOBA', '30');
INSERT INTO `ciudad` VALUES ('576', 'COSAMALOAPAN', '30');
INSERT INTO `ciudad` VALUES ('577', 'COSOLEACAQUE', '30');
INSERT INTO `ciudad` VALUES ('578', 'CUICHAPA', '30');
INSERT INTO `ciudad` VALUES ('579', 'CUITLÃHUAC', '30');
INSERT INTO `ciudad` VALUES ('580', 'EL HIGO', '30');
INSERT INTO `ciudad` VALUES ('581', 'FORTÃN DE LAS FLORES', '30');
INSERT INTO `ciudad` VALUES ('582', 'GENERAL MIGUEL ALEMÃN (POTRERO NUEVO)', '30');
INSERT INTO `ciudad` VALUES ('583', 'GUTIÃ‰RREZ ZAMORA', '30');
INSERT INTO `ciudad` VALUES ('584', 'HUATUSCO DE CHICUELLAR', '30');
INSERT INTO `ciudad` VALUES ('585', 'HUAYACOCOTLA', '30');
INSERT INTO `ciudad` VALUES ('586', 'HUILOAPAN DE CUAUHTÃ‰MOC', '30');
INSERT INTO `ciudad` VALUES ('587', 'ISLA', '30');
INSERT INTO `ciudad` VALUES ('588', 'IXTACZOQUITLÃN', '30');
INSERT INTO `ciudad` VALUES ('589', 'JÃLTIPAN DE MORELOS', '30');
INSERT INTO `ciudad` VALUES ('590', 'JOSÃ‰ CARDEL', '30');
INSERT INTO `ciudad` VALUES ('591', 'JUAN DÃAZ COVARRUBIAS', '30');
INSERT INTO `ciudad` VALUES ('592', 'JUAN RODRÃGUEZ CLARA', '30');
INSERT INTO `ciudad` VALUES ('593', 'LAS CHOAPAS', '30');
INSERT INTO `ciudad` VALUES ('594', 'LERDO DE TEJADA', '30');
INSERT INTO `ciudad` VALUES ('595', 'MINATITLÃN', '30');
INSERT INTO `ciudad` VALUES ('596', 'NARANJOS', '30');
INSERT INTO `ciudad` VALUES ('597', 'NOGALES', '30');
INSERT INTO `ciudad` VALUES ('598', 'ORIZABA', '30');
INSERT INTO `ciudad` VALUES ('599', 'PÃNUCO', '30');
INSERT INTO `ciudad` VALUES ('600', 'PAPANTLA DE OLARTE', '30');
INSERT INTO `ciudad` VALUES ('601', 'PARAJE NUEVO', '30');
INSERT INTO `ciudad` VALUES ('602', 'PASO DE OVEJAS', '30');
INSERT INTO `ciudad` VALUES ('603', 'PASO DEL MACHO', '30');
INSERT INTO `ciudad` VALUES ('604', 'PLATÃ“N SÃNCHEZ', '30');
INSERT INTO `ciudad` VALUES ('605', 'PLAYA VICENTE', '30');
INSERT INTO `ciudad` VALUES ('606', 'POZA RICA DE HIDALGO', '30');
INSERT INTO `ciudad` VALUES ('607', 'RÃO BLANCO', '30');
INSERT INTO `ciudad` VALUES ('608', 'SAN ANDRÃ‰S TUXTLA', '30');
INSERT INTO `ciudad` VALUES ('609', 'SAN RAFAEL', '30');
INSERT INTO `ciudad` VALUES ('610', 'SANTIAGO TUXTLA', '30');
INSERT INTO `ciudad` VALUES ('611', 'SIHUAPAN', '30');
INSERT INTO `ciudad` VALUES ('612', 'SOLEDAD DE DOBLADO', '30');
INSERT INTO `ciudad` VALUES ('613', 'TAMPICO ALTO', '30');
INSERT INTO `ciudad` VALUES ('614', 'TANTOYUCA', '30');
INSERT INTO `ciudad` VALUES ('615', 'TEMPOAL DE SÃNCHEZ', '30');
INSERT INTO `ciudad` VALUES ('616', 'TEZONAPA', '30');
INSERT INTO `ciudad` VALUES ('617', 'TIERRA BLANCA', '30');
INSERT INTO `ciudad` VALUES ('618', 'TIHUATLÃN', '30');
INSERT INTO `ciudad` VALUES ('619', 'TLACOJALPAN', '30');
INSERT INTO `ciudad` VALUES ('620', 'TLAPACOYAN', '30');
INSERT INTO `ciudad` VALUES ('621', 'TRES VALLES', '30');
INSERT INTO `ciudad` VALUES ('622', 'TÃšXPAM DE RODRÃGUEZ CANO', '30');
INSERT INTO `ciudad` VALUES ('623', 'VERACRUZ', '30');
INSERT INTO `ciudad` VALUES ('624', 'XALAPA-ENRÃQUEZ', '30');
INSERT INTO `ciudad` VALUES ('625', 'YECUATLA', '30');
INSERT INTO `ciudad` VALUES ('626', 'KANASÃN', '31');
INSERT INTO `ciudad` VALUES ('627', 'MÃ‰RIDA', '31');
INSERT INTO `ciudad` VALUES ('628', 'MOTUL DE CARRILLO PUERTO', '31');
INSERT INTO `ciudad` VALUES ('629', 'TICUL', '31');
INSERT INTO `ciudad` VALUES ('630', 'TIZIMÃN', '31');
INSERT INTO `ciudad` VALUES ('631', 'VALLADOLID', '31');
INSERT INTO `ciudad` VALUES ('632', 'CIUDAD CUAUHTÃ‰MOC', '32');
INSERT INTO `ciudad` VALUES ('633', 'FRESNILLO', '32');
INSERT INTO `ciudad` VALUES ('634', 'GUADALUPE', '32');
INSERT INTO `ciudad` VALUES ('635', 'JALPA', '32');
INSERT INTO `ciudad` VALUES ('636', 'JEREZ DE GARCÃA SALINAS', '32');
INSERT INTO `ciudad` VALUES ('637', 'JUAN ALDAMA', '32');
INSERT INTO `ciudad` VALUES ('638', 'LORETO', '32');
INSERT INTO `ciudad` VALUES ('639', 'LUIS MOYA', '32');
INSERT INTO `ciudad` VALUES ('640', 'MOYAHUA DE ESTRADA', '32');
INSERT INTO `ciudad` VALUES ('641', 'NOCHISTLÃN DE MEJÃA', '32');
INSERT INTO `ciudad` VALUES ('642', 'OJOCALIENTE', '32');
INSERT INTO `ciudad` VALUES ('643', 'RÃO GRANDE', '32');
INSERT INTO `ciudad` VALUES ('644', 'SOMBRERETE', '32');
INSERT INTO `ciudad` VALUES ('645', 'VALPARAÃSO', '32');
INSERT INTO `ciudad` VALUES ('646', 'VÃCTOR ROSALES', '32');
INSERT INTO `ciudad` VALUES ('647', 'VILLA DE COS', '32');
INSERT INTO `ciudad` VALUES ('648', 'VILLA HIDALGO', '32');
INSERT INTO `ciudad` VALUES ('649', 'VILLANUEVA', '32');
INSERT INTO `ciudad` VALUES ('650', 'ZACATECAS', '32');

-- ----------------------------
-- Table structure for coordinaciona
-- ----------------------------
DROP TABLE IF EXISTS `coordinaciona`;
CREATE TABLE `coordinaciona` (
  `coordinaciona` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Id Coordinación',
  `descripcion` varchar(45) NOT NULL COMMENT 'Descripción Coordinación',
  `programaedu` int(11) NOT NULL COMMENT 'Codigo carrera',
  PRIMARY KEY (`coordinaciona`),
  UNIQUE KEY `CO_codigo_UNIQUE` (`coordinaciona`),
  KEY `fk_coordinaciona_programaedu1` (`programaedu`),
  CONSTRAINT `fk_coordinaciona_programaedu1` FOREIGN KEY (`programaedu`) REFERENCES `programaedu` (`programaedu`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of coordinaciona
-- ----------------------------
INSERT INTO `coordinaciona` VALUES ('1', 'CONTABILIDAD BASICA', '1');
INSERT INTO `coordinaciona` VALUES ('2', 'CONTABILIDAD AVANZADA', '1');
INSERT INTO `coordinaciona` VALUES ('3', 'CONTABILIDAD DE COSTOS', '1');
INSERT INTO `coordinaciona` VALUES ('4', 'FINANZAS', '1');
INSERT INTO `coordinaciona` VALUES ('5', 'AUDITORIA', '1');
INSERT INTO `coordinaciona` VALUES ('6', 'IMPUESTOS', '1');
INSERT INTO `coordinaciona` VALUES ('7', 'MERCADOTECNIA', '1');
INSERT INTO `coordinaciona` VALUES ('8', 'RECURSOS HUMANOS', '1');
INSERT INTO `coordinaciona` VALUES ('9', 'PRODUCCION', '1');
INSERT INTO `coordinaciona` VALUES ('10', 'ADMINISTRACION BASICA', '1');
INSERT INTO `coordinaciona` VALUES ('11', 'ADMINISTRACION AVANZADA', '1');
INSERT INTO `coordinaciona` VALUES ('12', 'INFORMATICA', '1');
INSERT INTO `coordinaciona` VALUES ('13', 'MATEMATICAS', '1');
INSERT INTO `coordinaciona` VALUES ('14', 'CIENCIAS COMPUTACIONALES', '1');
INSERT INTO `coordinaciona` VALUES ('15', 'SISTEMAS DE INFORMACION', '1');
INSERT INTO `coordinaciona` VALUES ('16', 'PROGRAMACION', '1');
INSERT INTO `coordinaciona` VALUES ('17', 'ECONOMIA', '1');
INSERT INTO `coordinaciona` VALUES ('18', 'COMERCIO EXTERIOR', '1');
INSERT INTO `coordinaciona` VALUES ('19', 'DERECHO', '1');
INSERT INTO `coordinaciona` VALUES ('20', 'EMPRENDEDORES', '1');
INSERT INTO `coordinaciona` VALUES ('21', 'ASIGNATURAS DE APOYO', '1');
INSERT INTO `coordinaciona` VALUES ('22', 'SIN COORDINACION', '1');

-- ----------------------------
-- Table structure for directivopuesto
-- ----------------------------
DROP TABLE IF EXISTS `directivopuesto`;
CREATE TABLE `directivopuesto` (
  `directivopuesto` int(11) NOT NULL AUTO_INCREMENT COMMENT '1,2,3',
  `descripcion` varchar(15) NOT NULL COMMENT 'Director,subdirector, administrador',
  PRIMARY KEY (`directivopuesto`),
  UNIQUE KEY `DI_directivopuesto_UNIQUE` (`directivopuesto`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1 COMMENT='<double-click to overwrite multiple objects>';

-- ----------------------------
-- Records of directivopuesto
-- ----------------------------
INSERT INTO `directivopuesto` VALUES ('1', 'DIRECTOR');
INSERT INTO `directivopuesto` VALUES ('2', 'SUBDIRECTOR');
INSERT INTO `directivopuesto` VALUES ('3', 'ADMINISTRADOR');

-- ----------------------------
-- Table structure for directivosua
-- ----------------------------
DROP TABLE IF EXISTS `directivosua`;
CREATE TABLE `directivosua` (
  `empleado` int(11) NOT NULL COMMENT 'No empleado UABC que tiene  ese puesto',
  `uacademica` int(11) NOT NULL COMMENT 'Codigo uacademica',
  `directivopuesto` int(11) NOT NULL COMMENT 'Codigo puestodirectivo',
  PRIMARY KEY (`empleado`),
  KEY `fk_directivosua_uacademica1` (`uacademica`),
  KEY `fk_directivosua_directivopuesto1` (`directivopuesto`),
  CONSTRAINT `fk_directivosua_directivopuesto1` FOREIGN KEY (`directivopuesto`) REFERENCES `directivopuesto` (`directivopuesto`) ON UPDATE CASCADE,
  CONSTRAINT `fk_directivosua_empleados1` FOREIGN KEY (`empleado`) REFERENCES `empleados` (`empleado`) ON UPDATE CASCADE,
  CONSTRAINT `fk_directivosua_uacademica1` FOREIGN KEY (`uacademica`) REFERENCES `uacademica` (`uacademica`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of directivosua
-- ----------------------------
INSERT INTO `directivosua` VALUES ('1', '1', '1');

-- ----------------------------
-- Table structure for empleados
-- ----------------------------
DROP TABLE IF EXISTS `empleados`;
CREATE TABLE `empleados` (
  `empleado` int(11) NOT NULL COMMENT 'Numero de empleado UABC',
  `nombres` varchar(20) DEFAULT NULL COMMENT 'Nombre',
  `paterno` varchar(20) DEFAULT NULL COMMENT 'Paterno',
  `materno` varchar(20) DEFAULT NULL COMMENT 'Materno',
  `status` int(11) DEFAULT NULL COMMENT 'Status',
  `fec_nac` date DEFAULT NULL COMMENT 'Fecha nacimiento',
  `fec_ing` date DEFAULT NULL COMMENT 'Fecha ingreso',
  `cel` varchar(45) DEFAULT NULL COMMENT 'Celular',
  `telofna` varchar(45) DEFAULT NULL COMMENT 'Tel oficina',
  `tipocon` int(11) DEFAULT NULL COMMENT 'Tipo Contrato',
  `telcasa` varchar(45) DEFAULT NULL COMMENT 'Tel casa',
  `email` varchar(30) DEFAULT NULL COMMENT 'Email',
  `hrstope` int(11) DEFAULT NULL COMMENT 'Tope en hrs clase',
  `sexo` char(1) DEFAULT NULL COMMENT 'Sexo',
  PRIMARY KEY (`empleado`),
  UNIQUE KEY `DO_codigo_UNIQUE` (`empleado`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of empleados
-- ----------------------------
INSERT INTO `empleados` VALUES ('1', 'MARGARITA', 'RAMIREZ', 'RAMIREZ', '1', '2014-05-01', '2014-05-01', '044-666-6-34-02-36', '044-666-6-34-02-36', '1', '044-666-6-34-02-36', 'MAGUIRAM@UABC.EDU.MX', '40', 'F');
INSERT INTO `empleados` VALUES ('2', 'NORA DEL CARMEN', 'OZUNA', 'MILLAN', '1', '2014-05-01', '2014-05-01', '044-666-6-34-02-36', '044-666-6-34-02-36', '1', '044-666-6-34-02-36', 'NORA.OSUNA@UABC.EDU.MX', '40', 'F');
INSERT INTO `empleados` VALUES ('3', 'ESPERANZA', 'MANRIQUE', null, '1', '2014-05-01', '2014-05-01', '044-664-123-67-89', '044-664-123-67-89', '1', '044-664-123-67-89', 'EMANRIQUE@UABC.EDU.MX', '40', 'F');
INSERT INTO `empleados` VALUES ('4', 'EMMA SOFIA', 'CASTILLEJOS', 'CABALLERO', '1', '2014-05-01', '2014-05-01', 'O44-664-123-67-89', 'O44-664-123-67-89', '1', 'O44-664-123-67-89', 'EMA.CASTILLEJOS@UABC.EDU.MX', '40', 'F');
INSERT INTO `empleados` VALUES ('5', 'COORD. TRONCO COMUN', '', '', '1', '2014-05-01', '2014-05-01', '', '', '1', null, 'COORDINFORMATICA@UABC.EDU.MX', '0', 'F');
INSERT INTO `empleados` VALUES ('6', 'COORD. CONTADURIA', '', '', '1', '2014-05-01', '2014-05-01', '', '', '1', null, 'COORDINFORMATICA@UABC.EDU.MX', '0', 'F');
INSERT INTO `empleados` VALUES ('7', 'COORD. ADMON. DE EMP', '', '', '1', '2014-05-01', '2014-05-01', '', '', '1', null, 'COORDINFORMATICA@UABC.EDU.MX', '0', 'F');
INSERT INTO `empleados` VALUES ('8', 'COORD. INFORMATICA', '', '', '1', '2014-05-01', '2014-05-01', '', '', '1', null, 'COORDINFORMATICA@UABC.EDU.MX', '0', 'F');
INSERT INTO `empleados` VALUES ('9', 'COORD. NEGOCIOS INTE', '', '', '1', '2014-05-01', '2014-05-01', '', '', '1', null, 'COORDINFORMATICA@UABC.EDU.MX', '0', 'F');

-- ----------------------------
-- Table structure for esp_prog_edu
-- ----------------------------
DROP TABLE IF EXISTS `esp_prog_edu`;
CREATE TABLE `esp_prog_edu` (
  `especialidad` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Codigo Especificación Nivel Programa (SOLO POSTGRADO)',
  `descripcion` varchar(45) NOT NULL COMMENT 'Descripción Especificación Nivel Programa',
  `status` char(1) NOT NULL COMMENT 'Status esp nivel programa\n1=Activo',
  PRIMARY KEY (`especialidad`),
  UNIQUE KEY `ENP_codigo_UNIQUE` (`especialidad`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1 COMMENT='<double-click to overwrite multiple objects>';

-- ----------------------------
-- Records of esp_prog_edu
-- ----------------------------
INSERT INTO `esp_prog_edu` VALUES ('1', 'MTIC', '1');
INSERT INTO `esp_prog_edu` VALUES ('2', 'MC', '1');

-- ----------------------------
-- Table structure for estado
-- ----------------------------
DROP TABLE IF EXISTS `estado`;
CREATE TABLE `estado` (
  `estado` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Codigo estado',
  `descripcion` char(30) NOT NULL COMMENT 'Descripcion estado',
  `pais` int(11) NOT NULL COMMENT 'Codigo pais',
  PRIMARY KEY (`estado`),
  UNIQUE KEY `ES_codigo_UNIQUE` (`estado`),
  KEY `fk_estado_pais1` (`pais`),
  CONSTRAINT `fk_estado_pais1` FOREIGN KEY (`pais`) REFERENCES `pais` (`pais`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=latin1 COMMENT='<double-click to overwrite multiple objects>';

-- ----------------------------
-- Records of estado
-- ----------------------------
INSERT INTO `estado` VALUES ('1', 'AGUASCALIENTES', '144');
INSERT INTO `estado` VALUES ('2', 'BAJA CALIFORNIA', '144');
INSERT INTO `estado` VALUES ('3', 'BAJA CALIFORNIA SUR', '144');
INSERT INTO `estado` VALUES ('4', 'CAMPECHE', '144');
INSERT INTO `estado` VALUES ('5', 'COAHUILA DE ZARAGOZA', '144');
INSERT INTO `estado` VALUES ('6', 'COLIMA', '144');
INSERT INTO `estado` VALUES ('7', 'CHIAPAS', '144');
INSERT INTO `estado` VALUES ('8', 'CHIHUAHUA', '144');
INSERT INTO `estado` VALUES ('9', 'DISTRITO FEDERAL', '144');
INSERT INTO `estado` VALUES ('10', 'DURANGO', '144');
INSERT INTO `estado` VALUES ('11', 'GUANAJUATO', '144');
INSERT INTO `estado` VALUES ('12', 'GUERRERO', '144');
INSERT INTO `estado` VALUES ('13', 'HIDALGO', '144');
INSERT INTO `estado` VALUES ('14', 'JALISCO', '144');
INSERT INTO `estado` VALUES ('15', 'MEXICO', '144');
INSERT INTO `estado` VALUES ('16', 'MICHOACAN DE OCAMPO', '144');
INSERT INTO `estado` VALUES ('17', 'MORELOS', '144');
INSERT INTO `estado` VALUES ('18', 'NAYARIT', '144');
INSERT INTO `estado` VALUES ('19', 'NUEVO LEON', '144');
INSERT INTO `estado` VALUES ('20', 'OAXACA', '144');
INSERT INTO `estado` VALUES ('21', 'PUEBLA', '144');
INSERT INTO `estado` VALUES ('22', 'QUERETARO', '144');
INSERT INTO `estado` VALUES ('23', 'QUINTANA ROO', '144');
INSERT INTO `estado` VALUES ('24', 'SAN LUIS POTOSI', '144');
INSERT INTO `estado` VALUES ('25', 'SINALOA', '144');
INSERT INTO `estado` VALUES ('26', 'SONORA', '144');
INSERT INTO `estado` VALUES ('27', 'TABASCO', '144');
INSERT INTO `estado` VALUES ('28', 'TAMAULIPAS', '144');
INSERT INTO `estado` VALUES ('29', 'TLAXCALA', '144');
INSERT INTO `estado` VALUES ('30', 'VERACRUZ', '144');
INSERT INTO `estado` VALUES ('31', 'YUCATAN', '144');
INSERT INTO `estado` VALUES ('32', 'ZACATECAS', '144');

-- ----------------------------
-- Table structure for etapas
-- ----------------------------
DROP TABLE IF EXISTS `etapas`;
CREATE TABLE `etapas` (
  `etapa` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Código Etapa "B"/"D"/"T"',
  `descripcion` varchar(20) NOT NULL COMMENT 'Descripciónl plan',
  PRIMARY KEY (`etapa`),
  UNIQUE KEY `ET_codigo_UNIQUE` (`etapa`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of etapas
-- ----------------------------
INSERT INTO `etapas` VALUES ('1', 'BASICA');
INSERT INTO `etapas` VALUES ('2', 'DISCIPLINARIA');
INSERT INTO `etapas` VALUES ('3', 'TERMINAL');

-- ----------------------------
-- Table structure for nvprograma
-- ----------------------------
DROP TABLE IF EXISTS `nvprograma`;
CREATE TABLE `nvprograma` (
  `nivel` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Nivel (1,2,3)',
  `descripcion` varchar(15) NOT NULL COMMENT 'Licenciatura/Postgrado/doctorado',
  PRIMARY KEY (`nivel`),
  UNIQUE KEY `NV_codigo_UNIQUE` (`nivel`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1 COMMENT='<double-click to overwrite multiple objects>';

-- ----------------------------
-- Records of nvprograma
-- ----------------------------
INSERT INTO `nvprograma` VALUES ('1', 'LICENCIATURA');
INSERT INTO `nvprograma` VALUES ('2', 'POSTGRADO');
INSERT INTO `nvprograma` VALUES ('3', 'TECNICO');

-- ----------------------------
-- Table structure for pais
-- ----------------------------
DROP TABLE IF EXISTS `pais`;
CREATE TABLE `pais` (
  `pais` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Codigo pais',
  `descripcion` varchar(60) NOT NULL COMMENT 'Descripción pais',
  PRIMARY KEY (`pais`),
  UNIQUE KEY `PA_codigo_UNIQUE` (`pais`)
) ENGINE=InnoDB AUTO_INCREMENT=238 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of pais
-- ----------------------------
INSERT INTO `pais` VALUES ('1', 'AFGANISTAN');
INSERT INTO `pais` VALUES ('2', 'ALBANIA');
INSERT INTO `pais` VALUES ('3', 'ALEMANIA');
INSERT INTO `pais` VALUES ('4', 'ANDORRA');
INSERT INTO `pais` VALUES ('5', 'ANGOLA');
INSERT INTO `pais` VALUES ('6', 'ANGUILLA');
INSERT INTO `pais` VALUES ('7', 'ANTIGUA Y BARBUDA');
INSERT INTO `pais` VALUES ('8', 'ANTILLAS HOLANDESAS');
INSERT INTO `pais` VALUES ('9', 'ARABIA SAUDI');
INSERT INTO `pais` VALUES ('10', 'ARGELIA');
INSERT INTO `pais` VALUES ('11', 'ARGENTINA');
INSERT INTO `pais` VALUES ('12', 'ARMENIA');
INSERT INTO `pais` VALUES ('13', 'ARUBA');
INSERT INTO `pais` VALUES ('14', 'AUSTRALIA');
INSERT INTO `pais` VALUES ('15', 'AUSTRIA');
INSERT INTO `pais` VALUES ('16', 'AZERBAIYAN');
INSERT INTO `pais` VALUES ('17', 'BAHAMAS');
INSERT INTO `pais` VALUES ('18', 'BAHREIN');
INSERT INTO `pais` VALUES ('19', 'BANGLADESH');
INSERT INTO `pais` VALUES ('20', 'BARBADOS');
INSERT INTO `pais` VALUES ('22', 'BELGICA');
INSERT INTO `pais` VALUES ('23', 'BELICE');
INSERT INTO `pais` VALUES ('25', 'BERMUDAS');
INSERT INTO `pais` VALUES ('27', 'BOLIVIA');
INSERT INTO `pais` VALUES ('28', 'BOSNIA Y HERZEGOVINA');
INSERT INTO `pais` VALUES ('29', 'BOTSWANA');
INSERT INTO `pais` VALUES ('30', 'BRASIL');
INSERT INTO `pais` VALUES ('31', 'BRUNEI');
INSERT INTO `pais` VALUES ('32', 'BULGARIA');
INSERT INTO `pais` VALUES ('34', 'BURUNDI');
INSERT INTO `pais` VALUES ('35', 'CABO VERDE');
INSERT INTO `pais` VALUES ('36', 'CAMBOYA');
INSERT INTO `pais` VALUES ('37', 'CAMERUN');
INSERT INTO `pais` VALUES ('38', 'CANADA');
INSERT INTO `pais` VALUES ('40', 'CHILE');
INSERT INTO `pais` VALUES ('41', 'CHINA');
INSERT INTO `pais` VALUES ('42', 'CHIPRE');
INSERT INTO `pais` VALUES ('43', 'COLOMBIA');
INSERT INTO `pais` VALUES ('45', 'CONGO');
INSERT INTO `pais` VALUES ('46', 'COREA');
INSERT INTO `pais` VALUES ('47', 'COREA DEL NORTE ');
INSERT INTO `pais` VALUES ('48', 'COSTA DE MARFIL');
INSERT INTO `pais` VALUES ('49', 'COSTA RICA');
INSERT INTO `pais` VALUES ('50', 'CROACIA');
INSERT INTO `pais` VALUES ('51', 'CUBA');
INSERT INTO `pais` VALUES ('52', 'DINAMARCA');
INSERT INTO `pais` VALUES ('54', 'DOMINICA');
INSERT INTO `pais` VALUES ('55', 'ECUADOR');
INSERT INTO `pais` VALUES ('56', 'EGIPTO');
INSERT INTO `pais` VALUES ('57', 'EL SALVADOR');
INSERT INTO `pais` VALUES ('58', 'EMIRATOS ARABES UNIDOS');
INSERT INTO `pais` VALUES ('60', 'ESLOVENIA');
INSERT INTO `pais` VALUES ('61', 'ESPAÂ¥A');
INSERT INTO `pais` VALUES ('62', 'ESTADOS UNIDOS DE AMERICA');
INSERT INTO `pais` VALUES ('63', 'ESTONIA');
INSERT INTO `pais` VALUES ('64', 'ETIOPIA');
INSERT INTO `pais` VALUES ('65', 'FIJI');
INSERT INTO `pais` VALUES ('66', 'FILIPINAS');
INSERT INTO `pais` VALUES ('67', 'FINLANDIA');
INSERT INTO `pais` VALUES ('68', 'FRANCIA');
INSERT INTO `pais` VALUES ('69', 'GABON');
INSERT INTO `pais` VALUES ('70', 'GAMBIA');
INSERT INTO `pais` VALUES ('71', 'GEORGIA');
INSERT INTO `pais` VALUES ('72', 'GHANA');
INSERT INTO `pais` VALUES ('73', 'GIBRALTAR');
INSERT INTO `pais` VALUES ('74', 'GRANADA');
INSERT INTO `pais` VALUES ('75', 'GRECIA');
INSERT INTO `pais` VALUES ('76', 'GROENLANDIA');
INSERT INTO `pais` VALUES ('78', 'GUAM');
INSERT INTO `pais` VALUES ('79', 'GUATEMALA');
INSERT INTO `pais` VALUES ('80', 'GUAYANA FRANCESA');
INSERT INTO `pais` VALUES ('81', 'GUERNESEY');
INSERT INTO `pais` VALUES ('82', 'GUINEA');
INSERT INTO `pais` VALUES ('83', 'GUINEA ECUATORIAL');
INSERT INTO `pais` VALUES ('84', 'GUINEA-BISSAU');
INSERT INTO `pais` VALUES ('85', 'GUYANA');
INSERT INTO `pais` VALUES ('86', 'HAITI');
INSERT INTO `pais` VALUES ('87', 'HONDURAS');
INSERT INTO `pais` VALUES ('88', 'HONG KONG');
INSERT INTO `pais` VALUES ('89', 'HUNGRIA');
INSERT INTO `pais` VALUES ('90', 'INDIA');
INSERT INTO `pais` VALUES ('91', 'INDONESIA');
INSERT INTO `pais` VALUES ('92', 'IRAN');
INSERT INTO `pais` VALUES ('93', 'IRAQ');
INSERT INTO `pais` VALUES ('94', 'IRLANDA');
INSERT INTO `pais` VALUES ('95', 'ISLA DE MAN');
INSERT INTO `pais` VALUES ('96', 'ISLA NORFOLK');
INSERT INTO `pais` VALUES ('97', 'ISLANDIA');
INSERT INTO `pais` VALUES ('98', 'ISLAS ALAND');
INSERT INTO `pais` VALUES ('99', 'ISLAS CAIM?N');
INSERT INTO `pais` VALUES ('100', 'ISLAS COOK');
INSERT INTO `pais` VALUES ('101', 'ISLAS DEL CANAL');
INSERT INTO `pais` VALUES ('102', 'ISLAS FEROE');
INSERT INTO `pais` VALUES ('103', 'ISLAS MALVINAS');
INSERT INTO `pais` VALUES ('104', 'ISLAS MARIANAS DEL NORTE');
INSERT INTO `pais` VALUES ('105', 'ISLAS MARSHALL');
INSERT INTO `pais` VALUES ('106', 'ISLAS PITCAIRN');
INSERT INTO `pais` VALUES ('107', 'ISLAS SALOMON');
INSERT INTO `pais` VALUES ('108', 'ISLAS TURCAS Y CAICOS');
INSERT INTO `pais` VALUES ('109', 'ISLAS VIRGENES BRITANICAS');
INSERT INTO `pais` VALUES ('110', 'ISLAS V?RGENES DE LOS ESTADOS UNIDOS');
INSERT INTO `pais` VALUES ('111', 'ISRAEL');
INSERT INTO `pais` VALUES ('112', 'ITALIA');
INSERT INTO `pais` VALUES ('113', 'JAMAICA');
INSERT INTO `pais` VALUES ('114', 'JAPON');
INSERT INTO `pais` VALUES ('115', 'JERSEY');
INSERT INTO `pais` VALUES ('116', 'JORDANIA');
INSERT INTO `pais` VALUES ('117', 'KAZAJSTAN');
INSERT INTO `pais` VALUES ('118', 'KENIA');
INSERT INTO `pais` VALUES ('119', 'KIRGUISTAN');
INSERT INTO `pais` VALUES ('120', 'KIRIBATI');
INSERT INTO `pais` VALUES ('121', 'KUWAIT');
INSERT INTO `pais` VALUES ('122', 'LAOS');
INSERT INTO `pais` VALUES ('123', 'LESOTHO');
INSERT INTO `pais` VALUES ('124', 'LETONIA');
INSERT INTO `pais` VALUES ('125', 'LIBANO');
INSERT INTO `pais` VALUES ('126', 'LIBERIA');
INSERT INTO `pais` VALUES ('127', 'LIBIA');
INSERT INTO `pais` VALUES ('128', 'LIECHTENSTEIN');
INSERT INTO `pais` VALUES ('129', 'LITUANIA');
INSERT INTO `pais` VALUES ('130', 'LUXEMBURGO');
INSERT INTO `pais` VALUES ('131', 'MACAO');
INSERT INTO `pais` VALUES ('132', 'MACEDONIA ');
INSERT INTO `pais` VALUES ('133', 'MADAGASCAR');
INSERT INTO `pais` VALUES ('134', 'MALASIA');
INSERT INTO `pais` VALUES ('135', 'MALAWI');
INSERT INTO `pais` VALUES ('136', 'MALDIVAS');
INSERT INTO `pais` VALUES ('137', 'MALI');
INSERT INTO `pais` VALUES ('138', 'MALTA');
INSERT INTO `pais` VALUES ('139', 'MARRUECOS');
INSERT INTO `pais` VALUES ('140', 'MARTINICA');
INSERT INTO `pais` VALUES ('141', 'MAURICIO');
INSERT INTO `pais` VALUES ('142', 'MAURITANIA');
INSERT INTO `pais` VALUES ('143', 'MAYOTTE');
INSERT INTO `pais` VALUES ('144', 'MEXICO');
INSERT INTO `pais` VALUES ('145', 'MICRONESIA');
INSERT INTO `pais` VALUES ('146', 'MOLDAVIA');
INSERT INTO `pais` VALUES ('147', 'MONACO');
INSERT INTO `pais` VALUES ('148', 'MONGOLIA');
INSERT INTO `pais` VALUES ('149', 'MONTENEGRO');
INSERT INTO `pais` VALUES ('150', 'MONTSERRAT');
INSERT INTO `pais` VALUES ('151', 'MOZAMBIQUE');
INSERT INTO `pais` VALUES ('152', 'MYANMAR');
INSERT INTO `pais` VALUES ('153', 'NAMIBIA');
INSERT INTO `pais` VALUES ('154', 'NAURU');
INSERT INTO `pais` VALUES ('155', 'NEPAL');
INSERT INTO `pais` VALUES ('156', 'NICARAGUA');
INSERT INTO `pais` VALUES ('157', 'NIGER');
INSERT INTO `pais` VALUES ('158', 'NIGERIA');
INSERT INTO `pais` VALUES ('159', 'NIUE');
INSERT INTO `pais` VALUES ('160', 'NORUEGA');
INSERT INTO `pais` VALUES ('161', 'NUEVA CALEDONIA');
INSERT INTO `pais` VALUES ('162', 'NUEVA ZELANDA');
INSERT INTO `pais` VALUES ('163', 'OMAN');
INSERT INTO `pais` VALUES ('164', 'PAISES BAJOS');
INSERT INTO `pais` VALUES ('165', 'PAKISTAN');
INSERT INTO `pais` VALUES ('166', 'PALAOS');
INSERT INTO `pais` VALUES ('167', 'PALESTINA');
INSERT INTO `pais` VALUES ('168', 'PANAMA');
INSERT INTO `pais` VALUES ('169', 'PAPUA NUEVA GUINEA');
INSERT INTO `pais` VALUES ('170', 'PARAGUAY');
INSERT INTO `pais` VALUES ('171', 'PERU');
INSERT INTO `pais` VALUES ('172', 'POLINESIA FRANCESA');
INSERT INTO `pais` VALUES ('173', 'POLONIA');
INSERT INTO `pais` VALUES ('174', 'PORTUGAL');
INSERT INTO `pais` VALUES ('175', 'PUERTO RICO');
INSERT INTO `pais` VALUES ('176', 'QATAR');
INSERT INTO `pais` VALUES ('177', 'REINO UNIDO');
INSERT INTO `pais` VALUES ('178', 'REP.DEMOCRATICA DEL CONGO');
INSERT INTO `pais` VALUES ('179', 'REPUBLICA CENTROAFRICANA');
INSERT INTO `pais` VALUES ('180', 'REPUBLICA CHECA');
INSERT INTO `pais` VALUES ('181', 'REPUBLICA DOMINICANA');
INSERT INTO `pais` VALUES ('182', 'REPUBLICA ESLOVACA');
INSERT INTO `pais` VALUES ('183', 'REUNION');
INSERT INTO `pais` VALUES ('184', 'RUANDA');
INSERT INTO `pais` VALUES ('185', 'RUMANIA');
INSERT INTO `pais` VALUES ('186', 'RUSIA');
INSERT INTO `pais` VALUES ('187', 'SAHARA OCCIDENTAL');
INSERT INTO `pais` VALUES ('188', 'SAMOA');
INSERT INTO `pais` VALUES ('189', 'SAMOA AMERICANA');
INSERT INTO `pais` VALUES ('190', 'SAN BARTOLOME');
INSERT INTO `pais` VALUES ('191', 'SAN CRISTOBAL Y NIEVES');
INSERT INTO `pais` VALUES ('192', 'SAN MARINO');
INSERT INTO `pais` VALUES ('193', 'SAN MARTIN (PARTE FRANCESA)');
INSERT INTO `pais` VALUES ('194', 'SAN PEDRO Y MIQUELON ');
INSERT INTO `pais` VALUES ('195', 'SAN VICENTE Y LAS GRANADINAS');
INSERT INTO `pais` VALUES ('196', 'SANTA HELENA');
INSERT INTO `pais` VALUES ('197', 'SANTA LUCIA');
INSERT INTO `pais` VALUES ('198', 'SANTA SEDE');
INSERT INTO `pais` VALUES ('199', 'SANTO TOME Y PRINCIPE');
INSERT INTO `pais` VALUES ('200', 'SENEGAL');
INSERT INTO `pais` VALUES ('201', 'SERBIA');
INSERT INTO `pais` VALUES ('202', 'SEYCHELLES');
INSERT INTO `pais` VALUES ('203', 'SIERRA LEONA');
INSERT INTO `pais` VALUES ('204', 'SINGAPUR');
INSERT INTO `pais` VALUES ('205', 'SIRIA');
INSERT INTO `pais` VALUES ('206', 'SOMALIA');
INSERT INTO `pais` VALUES ('207', 'SRI LANKA');
INSERT INTO `pais` VALUES ('208', 'SUDAFRICA');
INSERT INTO `pais` VALUES ('209', 'SUDAN');
INSERT INTO `pais` VALUES ('210', 'SUECIA');
INSERT INTO `pais` VALUES ('211', 'SUIZA');
INSERT INTO `pais` VALUES ('212', 'SURINAM');
INSERT INTO `pais` VALUES ('213', 'SVALBARD Y JAN MAYEN');
INSERT INTO `pais` VALUES ('214', 'SWAZILANDIA');
INSERT INTO `pais` VALUES ('215', 'TADYIKISTAN');
INSERT INTO `pais` VALUES ('216', 'TAILANDIA');
INSERT INTO `pais` VALUES ('217', 'TANZANIA');
INSERT INTO `pais` VALUES ('218', 'TIMOR ORIENTAL');
INSERT INTO `pais` VALUES ('219', 'TOGO');
INSERT INTO `pais` VALUES ('220', 'TOKELAU');
INSERT INTO `pais` VALUES ('221', 'TONGA');
INSERT INTO `pais` VALUES ('222', 'TRINIDAD Y TOBAGO');
INSERT INTO `pais` VALUES ('223', 'TUNEZ');
INSERT INTO `pais` VALUES ('224', 'TURKMENISTAN');
INSERT INTO `pais` VALUES ('225', 'TURQUIA');
INSERT INTO `pais` VALUES ('226', 'TUVALU');
INSERT INTO `pais` VALUES ('227', 'UCRANIA');
INSERT INTO `pais` VALUES ('228', 'UGANDA');
INSERT INTO `pais` VALUES ('229', 'URUGUAY');
INSERT INTO `pais` VALUES ('230', 'UZBEKISTAN');
INSERT INTO `pais` VALUES ('231', 'VANUATU');
INSERT INTO `pais` VALUES ('232', 'VENEZUELA');
INSERT INTO `pais` VALUES ('233', 'VIETNAM');
INSERT INTO `pais` VALUES ('234', 'WALLIS Y FORTUNA');
INSERT INTO `pais` VALUES ('235', 'YEMEN');
INSERT INTO `pais` VALUES ('236', 'ZAMBIA');
INSERT INTO `pais` VALUES ('237', 'ZIMBABWE');

-- ----------------------------
-- Table structure for periodo_prog_edu
-- ----------------------------
DROP TABLE IF EXISTS `periodo_prog_edu`;
CREATE TABLE `periodo_prog_edu` (
  `periodo_pedu` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Tipo: 1=semestral/2=cuatrimestral',
  `descripcion` varchar(15) NOT NULL COMMENT 'Descripcion: semestral, cuatrimestral',
  PRIMARY KEY (`periodo_pedu`),
  UNIQUE KEY `TP_codigo_UNIQUE` (`periodo_pedu`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of periodo_prog_edu
-- ----------------------------
INSERT INTO `periodo_prog_edu` VALUES ('1', 'SEMESTRAL');
INSERT INTO `periodo_prog_edu` VALUES ('2', 'CUATRIMESTRAL');
INSERT INTO `periodo_prog_edu` VALUES ('3', 'TRIMESTRAL');
INSERT INTO `periodo_prog_edu` VALUES ('4', 'SABATINO');

-- ----------------------------
-- Table structure for planestudio
-- ----------------------------
DROP TABLE IF EXISTS `planestudio`;
CREATE TABLE `planestudio` (
  `plan` int(11) NOT NULL COMMENT 'Código Plan (Año+Semestre)',
  `programaedu` int(11) NOT NULL COMMENT 'Carrera',
  PRIMARY KEY (`plan`,`programaedu`),
  KEY `fk_planestudio_programaedu1` (`programaedu`),
  CONSTRAINT `plan_fk` FOREIGN KEY (`plan`) REFERENCES `planestudiodesc` (`plan`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `programaedu_fk` FOREIGN KEY (`programaedu`) REFERENCES `programaedu` (`programaedu`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of planestudio
-- ----------------------------
INSERT INTO `planestudio` VALUES ('20092', '1');
INSERT INTO `planestudio` VALUES ('20101', '1');
INSERT INTO `planestudio` VALUES ('20092', '2');
INSERT INTO `planestudio` VALUES ('20101', '2');
INSERT INTO `planestudio` VALUES ('20092', '3');
INSERT INTO `planestudio` VALUES ('20101', '3');
INSERT INTO `planestudio` VALUES ('20092', '4');
INSERT INTO `planestudio` VALUES ('20092', '5');
INSERT INTO `planestudio` VALUES ('20092', '6');
INSERT INTO `planestudio` VALUES ('20092', '7');

-- ----------------------------
-- Table structure for planestudiodesc
-- ----------------------------
DROP TABLE IF EXISTS `planestudiodesc`;
CREATE TABLE `planestudiodesc` (
  `plan` int(11) NOT NULL COMMENT 'Codigo plan estudio',
  `descripcion` varchar(35) NOT NULL COMMENT 'Descripción plan  ("PLAN DE ESTUDIOS "+Año+" "+Semestre)',
  `credpracticas` int(11) NOT NULL COMMENT 'Total Créditos practicas',
  `feciniciovig` date NOT NULL COMMENT 'Fecha inicio Vigencia',
  `fecfinvig` date NOT NULL COMMENT 'Fecha Fin Vigencia',
  `nivel` int(11) NOT NULL,
  PRIMARY KEY (`plan`),
  KEY `fk_planestudiodesc_planestudio1` (`plan`),
  KEY `plan_nivel_fk` (`nivel`),
  CONSTRAINT `plan_nivel_fk` FOREIGN KEY (`nivel`) REFERENCES `nvprograma` (`nivel`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of planestudiodesc
-- ----------------------------
INSERT INTO `planestudiodesc` VALUES ('20092', 'Plan 2009 2', '200', '2014-06-19', '2015-02-10', '1');
INSERT INTO `planestudiodesc` VALUES ('20101', 'Otro plan', '200', '2014-06-19', '2014-06-30', '2');

-- ----------------------------
-- Table structure for programaedu
-- ----------------------------
DROP TABLE IF EXISTS `programaedu`;
CREATE TABLE `programaedu` (
  `programaedu` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Código Programa Educativo( Carrera)',
  `descripcion` varchar(60) NOT NULL COMMENT 'Descripción detallenivprog (carrera)',
  `status` int(11) NOT NULL COMMENT '1=Activa/0=Baja',
  `empleado` int(11) NOT NULL COMMENT 'No empl. coordinador',
  `uacademica` int(11) NOT NULL COMMENT 'Uacademica',
  `especialidad` int(11) DEFAULT NULL COMMENT 'Especialidad programa educativo',
  `nivel` int(11) NOT NULL COMMENT 'Codigo nivel pe (para especificar Licenciatura/Postgrado/doctorado)',
  `periodo_pedu` int(11) NOT NULL COMMENT 'Codigo periodo pe para especificar 1=semestral/2=cuatrimestral',
  PRIMARY KEY (`programaedu`),
  UNIQUE KEY `DNP_codigo_UNIQUE` (`programaedu`),
  KEY `fk_programaedu_empleados1` (`empleado`),
  KEY `fk_programaedu_uacademica1` (`uacademica`),
  KEY `fk_programaedu_nvprograma1` (`nivel`),
  KEY `fk_programaedu_periodo_prog_edu1` (`periodo_pedu`),
  KEY `fk_programaedu_esp_prog_edu1` (`especialidad`),
  CONSTRAINT `fk_programaedu_empleados1` FOREIGN KEY (`empleado`) REFERENCES `empleados` (`empleado`) ON UPDATE CASCADE,
  CONSTRAINT `fk_programaedu_esp_prog_edu1` FOREIGN KEY (`especialidad`) REFERENCES `esp_prog_edu` (`especialidad`) ON UPDATE CASCADE,
  CONSTRAINT `fk_programaedu_nvprograma1` FOREIGN KEY (`nivel`) REFERENCES `nvprograma` (`nivel`) ON UPDATE CASCADE,
  CONSTRAINT `fk_programaedu_periodo_prog_edu1` FOREIGN KEY (`periodo_pedu`) REFERENCES `periodo_prog_edu` (`periodo_pedu`) ON UPDATE CASCADE,
  CONSTRAINT `fk_programaedu_uacademica1` FOREIGN KEY (`uacademica`) REFERENCES `uacademica` (`uacademica`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=latin1 COMMENT='<double-click to overwrite multiple objects>';

-- ----------------------------
-- Records of programaedu
-- ----------------------------
INSERT INTO `programaedu` VALUES ('1', 'MEDICINA', '1', '1', '1', null, '1', '1');
INSERT INTO `programaedu` VALUES ('2', 'CONTADURIA', '1', '2', '1', null, '1', '1');
INSERT INTO `programaedu` VALUES ('3', 'ADMON. DE EMPRESAS', '1', '3', '1', null, '1', '1');
INSERT INTO `programaedu` VALUES ('4', 'INFORMATICA', '1', '4', '1', null, '1', '1');
INSERT INTO `programaedu` VALUES ('5', 'NEGOCIOS INTERNACIONALES', '1', '5', '1', null, '1', '1');
INSERT INTO `programaedu` VALUES ('6', 'ARTES', '1', '1', '1', '2', '2', '2');
INSERT INTO `programaedu` VALUES ('7', 'CIENCIAS COMPUTACIONALES', '1', '1', '1', '2', '2', '3');

-- ----------------------------
-- Table structure for p_ua
-- ----------------------------
DROP TABLE IF EXISTS `p_ua`;
CREATE TABLE `p_ua` (
  `programaedu` int(11) NOT NULL COMMENT 'Programa educativo',
  `uaprendizaje` int(11) NOT NULL COMMENT 'Unidad de aprendizaje',
  PRIMARY KEY (`programaedu`,`uaprendizaje`),
  KEY `fk_p_ua_programaedu1` (`programaedu`),
  KEY `fk_p_ua_uaprendizaje1` (`uaprendizaje`),
  CONSTRAINT `fk_p_ua_programaedu1` FOREIGN KEY (`programaedu`) REFERENCES `programaedu` (`programaedu`) ON UPDATE CASCADE,
  CONSTRAINT `fk_p_ua_uaprendizaje1` FOREIGN KEY (`uaprendizaje`) REFERENCES `uaprendizaje` (`uaprendizaje`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT='<double-click to overwrite multiple objects>';

-- ----------------------------
-- Records of p_ua
-- ----------------------------
INSERT INTO `p_ua` VALUES ('1', '11236');
INSERT INTO `p_ua` VALUES ('1', '11237');
INSERT INTO `p_ua` VALUES ('2', '11236');

-- ----------------------------
-- Table structure for reqseriacion
-- ----------------------------
DROP TABLE IF EXISTS `reqseriacion`;
CREATE TABLE `reqseriacion` (
  `reqseriacion` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Reqseriacion ("O","C")',
  `descripcion` varchar(15) NOT NULL COMMENT 'Obligada/conveniente',
  PRIMARY KEY (`reqseriacion`),
  UNIQUE KEY `RS_codigo_UNIQUE` (`reqseriacion`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1 COMMENT='<double-click to overwrite multiple objects>';

-- ----------------------------
-- Records of reqseriacion
-- ----------------------------
INSERT INTO `reqseriacion` VALUES ('1', 'SIN SERIACION');
INSERT INTO `reqseriacion` VALUES ('2', 'OBLIGATORIA');
INSERT INTO `reqseriacion` VALUES ('3', 'SUGERIDA');

-- ----------------------------
-- Table structure for uacademica
-- ----------------------------
DROP TABLE IF EXISTS `uacademica`;
CREATE TABLE `uacademica` (
  `uacademica` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Codigo Facultad',
  `descripshort` varchar(10) NOT NULL COMMENT 'Descripcion (FCQ, FCA)',
  `descripcion` varchar(60) NOT NULL COMMENT 'Descripcion Facultad',
  `campus` int(11) NOT NULL COMMENT 'Codigo campus',
  PRIMARY KEY (`uacademica`),
  UNIQUE KEY `UAC_codigo_UNIQUE` (`uacademica`),
  KEY `fk_uacademica_campus1` (`campus`),
  CONSTRAINT `fk_uacademica_campus1` FOREIGN KEY (`campus`) REFERENCES `campus` (`campus`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of uacademica
-- ----------------------------
INSERT INTO `uacademica` VALUES ('1', 'FCA', 'FACULTAD DE CONTADURIA Y ADMINISTRACION', '1');
INSERT INTO `uacademica` VALUES ('2', 'FCQI', 'FACULTAD DE CIENCIAS QUIMICAS E INGENIERIA', '1');
INSERT INTO `uacademica` VALUES ('3', 'FHCS', 'FACULTAD DE HUMANIDADES Y CIENCIAS SOCIALES', '1');
INSERT INTO `uacademica` VALUES ('4', 'FD', 'FACULTAD DE DERECHO', '1');
INSERT INTO `uacademica` VALUES ('5', 'FERI', 'FACULTAD DE ECONOMIA Y RELACIONES INTERNACIONALES', '1');
INSERT INTO `uacademica` VALUES ('6', 'FIN', 'FACULTAD DE INGENIERIA Y NEGOCIOS', '1');
INSERT INTO `uacademica` VALUES ('7', 'FMP', 'FACULTAD DE MEDICINA Y PSICOLOGIA', '1');
INSERT INTO `uacademica` VALUES ('8', 'FO', 'FACULTAD DE ODONTOLOGIA', '1');
INSERT INTO `uacademica` VALUES ('9', 'FTM', 'FACULTAD DE TURISMO Y MERCADOTECNIA', '1');
INSERT INTO `uacademica` VALUES ('10', 'FA', 'FACULTAD DE ARTES', '1');

-- ----------------------------
-- Table structure for uaprendizaje
-- ----------------------------
DROP TABLE IF EXISTS `uaprendizaje`;
CREATE TABLE `uaprendizaje` (
  `uaprendizaje` int(11) NOT NULL COMMENT 'Código uaprendizaje (SOLO NUMERICOS)',
  `plan` int(11) NOT NULL COMMENT 'Codigo plan estudio',
  `descripcionmat` varchar(60) CHARACTER SET latin1 NOT NULL COMMENT 'Descripción  uaprendizaje',
  `HC` int(11) NOT NULL COMMENT 'Horas Clase',
  `HL` int(11) NOT NULL COMMENT 'Horas Laboratorio',
  `HT` int(11) NOT NULL COMMENT 'Horas Taller',
  `HPC` int(11) NOT NULL COMMENT 'Horas',
  `HCL` int(11) NOT NULL COMMENT 'Horas Clinica',
  `HE` int(11) NOT NULL COMMENT 'Horas Extra',
  `creditos` int(11) NOT NULL COMMENT 'Numero de Créditos\n1Hr Clase= 2c',
  `semestre` int(255) DEFAULT NULL,
  `fec_aut` date DEFAULT NULL COMMENT 'Fecha autorización',
  `observa` varchar(60) CHARACTER SET latin1 DEFAULT NULL COMMENT 'Observaciones',
  `caracter` int(11) NOT NULL COMMENT 'Codigo caracter para especificar 1=Obligatoria/2=Optativa',
  `reqseriacion` int(11) NOT NULL COMMENT 'Codigo req seriacion para especificar Obligada/conveniente',
  `claveD` int(11) DEFAULT NULL COMMENT 'Clave materia dependiente.',
  `etapa` int(11) NOT NULL COMMENT 'Código etapa para especificar Basica, Disciplinario, Terminal',
  `coordinaciona` int(11) NOT NULL COMMENT 'Codigo coordinacion area',
  PRIMARY KEY (`uaprendizaje`),
  KEY `fk_uaprendizaje_caracter1` (`caracter`),
  KEY `fk_uaprendizaje_reqseriacion1` (`reqseriacion`),
  KEY `fk_uaprendizaje_etapas1` (`etapa`),
  KEY `fk_uaprendizaje_coordinaciona1` (`coordinaciona`),
  KEY `fk_uaprendizaje_planestudio1` (`plan`),
  KEY `fk_uaprendizaje_uaprendizaje1` (`claveD`),
  CONSTRAINT `fk_uaprendizaje_caracter1` FOREIGN KEY (`caracter`) REFERENCES `caracter` (`caracter`) ON UPDATE CASCADE,
  CONSTRAINT `fk_uaprendizaje_etapas1` FOREIGN KEY (`etapa`) REFERENCES `etapas` (`etapa`) ON UPDATE CASCADE,
  CONSTRAINT `fk_uaprendizaje_planestudio1` FOREIGN KEY (`plan`) REFERENCES `planestudiodesc` (`plan`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_uaprendizaje_reqseriacion1` FOREIGN KEY (`reqseriacion`) REFERENCES `reqseriacion` (`reqseriacion`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='<double-click to overwrite multiple objects>';

-- ----------------------------
-- Records of uaprendizaje
-- ----------------------------
INSERT INTO `uaprendizaje` VALUES ('11236', '20101', 'MATEMATICAS I', '1', '2', '3', '5', '7', '4', '22', '1', '2014-07-09', 'VAMOS A VER QUE TAL', '1', '1', null, '1', '1');
INSERT INTO `uaprendizaje` VALUES ('11237', '20101', 'MATEMATICAS II', '0', '0', '0', '0', '0', '0', '0', '1', '2014-07-09', 'VAMOS A VER QUE TAL', '1', '2', '11236', '1', '5');

-- ----------------------------
-- Table structure for uaprendizaje_copy
-- ----------------------------
DROP TABLE IF EXISTS `uaprendizaje_copy`;
CREATE TABLE `uaprendizaje_copy` (
  `uaprendizaje` int(11) NOT NULL COMMENT 'Código uaprendizaje (SOLO NUMERICOS)',
  `plan` int(11) NOT NULL COMMENT 'Codigo plan estudio',
  `descripcionmat` varchar(60) CHARACTER SET latin1 NOT NULL COMMENT 'Descripción  uaprendizaje',
  `HC` int(11) NOT NULL COMMENT 'Horas Clase',
  `HL` int(11) NOT NULL COMMENT 'Horas Laboratorio',
  `HT` int(11) NOT NULL COMMENT 'Horas Taller',
  `HPC` int(11) NOT NULL COMMENT 'Horas',
  `HCL` int(11) NOT NULL COMMENT 'Horas Clinica',
  `HE` int(11) NOT NULL COMMENT 'Horas Extra',
  `creditos` int(11) NOT NULL COMMENT 'Numero de Créditos\n1Hr Clase= 2c',
  `fec_aut` date DEFAULT NULL COMMENT 'Fecha autorización',
  `observa` varchar(60) CHARACTER SET latin1 DEFAULT NULL COMMENT 'Observaciones',
  `caracter` int(11) NOT NULL COMMENT 'Codigo caracter para especificar 1=Obligatoria/2=Optativa',
  `reqseriacion` int(11) NOT NULL COMMENT 'Codigo req seriacion para especificar Obligada/conveniente',
  `claveD` int(11) DEFAULT NULL COMMENT 'Clave materia dependiente.',
  `etapa` int(11) NOT NULL COMMENT 'Código etapa para especificar Basica, Disciplinario, Terminal',
  `coordinaciona` int(11) NOT NULL COMMENT 'Codigo coordinacion area',
  PRIMARY KEY (`uaprendizaje`),
  KEY `fk_uaprendizaje_caracter1` (`caracter`),
  KEY `fk_uaprendizaje_reqseriacion1` (`reqseriacion`),
  KEY `fk_uaprendizaje_etapas1` (`etapa`),
  KEY `fk_uaprendizaje_coordinaciona1` (`coordinaciona`),
  KEY `fk_uaprendizaje_planestudio1` (`plan`),
  KEY `fk_uaprendizaje_uaprendizaje1` (`claveD`),
  CONSTRAINT `uaprendizaje_copy_ibfk_1` FOREIGN KEY (`caracter`) REFERENCES `caracter` (`caracter`) ON UPDATE CASCADE,
  CONSTRAINT `uaprendizaje_copy_ibfk_2` FOREIGN KEY (`etapa`) REFERENCES `etapas` (`etapa`) ON UPDATE CASCADE,
  CONSTRAINT `uaprendizaje_copy_ibfk_3` FOREIGN KEY (`plan`) REFERENCES `planestudiodesc` (`plan`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `uaprendizaje_copy_ibfk_4` FOREIGN KEY (`reqseriacion`) REFERENCES `reqseriacion` (`reqseriacion`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='<double-click to overwrite multiple objects>';

-- ----------------------------
-- Records of uaprendizaje_copy
-- ----------------------------

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `last_name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `address` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `phone` int(11) NOT NULL,
  `campus` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `unidad` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `ua` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `username` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `level` tinyint(1) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `remember_token` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`),
  UNIQUE KEY `users_username_unique` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ----------------------------
-- Records of users
-- ----------------------------
INSERT INTO `users` VALUES ('8', 'Ivan', 'Duarte', 'wolfogan@gmail.com', 'Real de Calacoaya 7810-3B', '6450706', 'TIJUANA', 'ENSENADA', 'FCA', 'LoganX', '$2y$10$k8fT0GW/Obx8KgZU4hVufOt/stcuq3Y9Z8/9StZEMuLWOCmjfK1hO', '0', '2014-04-19 12:30:58', '2014-04-19 12:30:58', '');
INSERT INTO `users` VALUES ('9', 'Cynthia', 'Duarte', 'zyntya@hotmail.com', 'Col. Nueva Tijuana', '6233987', 'TIJUANA', 'VALLE DE LA TRINIDAD', 'FD', 'Tikita', '$2y$10$9qAw9XKA/BtqYRg5WS087.3WjqG.eH0P8.JiLsY7BF4nBAZAPJ752', '1', '2014-04-19 12:30:58', '2014-07-02 20:08:31', 'g1RLHU6OU8m6AQBiZeP3SyHcYKYaJZl3unFTdGCvj2saH6vex0oLMzrZx7if');
INSERT INTO `users` VALUES ('10', 'Raúl', 'Contreras', 'Raulito21@gmail.com', 'Calle 9 de julio #244', '52224799', 'TIJUANA', 'VALLE DE LAS PALMAS', 'FCA', 'ra21', '$2y$10$BCYlojviBdFVCG4jfpdcluYJWLW/2/gGIjDsgxPcKWRx09DpE1Oce', '0', '2014-04-19 12:31:10', '2014-04-19 12:31:10', '');
INSERT INTO `users` VALUES ('11', 'Juanelon', 'Rosado de la colina', 'paquito@gmail.com', 'Real de patito 50', '6457896', 'TIJUANA', 'HISTORICO', 'FHD', 'paquito', '$2y$10$NFJnp7SweU./sBw/YqBuM.Fg1mHuVjngo2e55Z/p9w.JxpliC6QlC', '0', '2014-04-21 08:08:27', '2014-04-21 10:03:15', '');
INSERT INTO `users` VALUES ('17', 'unice', 'unice', 'unice@gmail.com', 'nose donde vive', '2147483647', 'TIJUANA', 'HISTORICO', 'FD', 'uni', '$2y$10$T3ztXBdUMPxZGvOSyNk8wuSKCiX2gYu7WSLZ9ANkm5XVBda2Rm2Ye', '1', '2014-04-25 02:42:07', '2014-04-25 02:42:07', '');
